<a href="https://colab.research.google.com/github/Thaizalu/Aprendizado/blob/main/Pandas_I_O_trabalhando_com_diferentes_formatos_de_arquivo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Material de Estudo de Pandas



# Aula 01

In [1]:
import pandas as pd #importando a biblioteca pandas

Para facilitar a escrita, costumamos apelidar as bibliotecas. Por isso abreviamos Pandas para pd.

Para executar a célula podemos clicar na seta localizada à esquerda ou usar o atalho "Shift + Enter". Vamos executar.

Em seguida, vamos criar uma variável chamada url com o endereço de onde estão os dados brutos do nosso arquivo. Podemos colocar o endereço da URL em que os dados brutos estão dentro aspas simples ou aspas duplas, tanto faz. Aqui vou usar aspas simples. Vamos executar esta célula:

In [2]:
url = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/superstore_data.csv'

Em seguida, faremos a leitura desse arquivo. Para isso, criaremos uma variável chamada dados_mercado que será igual a pd.read_csv. A read_csv é a função que consegue fazer a leitura de um arquivo .csv.

Vamos abrir parênteses e, dentro deles, passaremos a variável na qual armazenamos o endereço URL dos dados brutos.

In [3]:
dados_mercado = pd.read_csv(url)

A função read_csv vai pegar esse endereço que passamos e ler esses dados em um objeto Pandas chamado DataFrame. Ele é muito parecido com uma tabela, vamos visualizar isso agora.

Para visualizar esse DataFrame executaremos o comando:

In [4]:
dados_mercado.head()

Id  Year_Birth   Education Marital_Status   Income  Kidhome  Teenhome  \
0   1826        1970  Graduation       Divorced  84835.0        0         0   
1      1        1961  Graduation         Single  57091.0        0         0   
2  10476        1958  Graduation        Married  67267.0        0         1   
3   1386        1967  Graduation       Together  32474.0        1         1   
4   5371        1989  Graduation         Single  21474.0        1         0   

  Dt_Customer  Recency  MntWines  ...  MntFishProducts  MntSweetProducts  \
0   6/16/2014        0       189  ...              111               189   
1   6/15/2014        0       464  ...                7                 0   
2   5/13/2014        0       134  ...               15                 2   
3   11/5/2014        0        10  ...                0                 0   
4    8/4/2014        0         6  ...               11                 0   

   MntGoldProds  NumDealsPurchases  NumWebPurchases  NumCatalogPurchases  \
0           218                  1                4                    4   
1            37                  1                7                    3   
2            30                  1                3                    2   
3             0                  1                1                    0   
4            34                  2                3                    1   

   NumStorePurchases  NumWebVisitsMonth  Response  Complain  
0                  6                  1         1         0  
1                  7                  5         1         0  
2                  5                  2         0         0  
3                  2                  7         0         0  
4                  2                  7         1         0  

[5 rows x 22 columns]

A função read() permite a visualização das 5 primeiras linhas desse DataFrame.

Ao executar a célula do comando dados_mercado.head() teremos algo semelhante a uma tabela contendo os nossos dados. Temos 5 linhas e 22 colunas.

Quais informações nós temos? O Id de cada cliente, que é um código diferente para cada uma das pessoas; o ano de nascimento; nível de escolaridade; estado civil; rendimento anual; e várias colunas com informações sobre as compras que essas pessoas fizeram no mercado. Temos bastante informação.

Beleza! Conseguimos abrir esse arquivo .csv utilizando a biblioteca Pandas no Google Colab, mas tem um detalhe: os arquivos .csv nem sempre são separados por vírgulas. Às vezes eles podem estar separados por ponto e vírgula (;).

O que acontece nesse caso? Como podemos fazer a leitura?

Para entendermos isso, preparei um arquivo igual ao que usamos nesse vídeo, mas agora ele está separado por ponto e vírgula. É um arquivo chamado superstore_data_ponto_virgula.csv.

In [5]:
url_2 = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/superstore_data_ponto_virgula.csv'

Em seguida, criaremos uma nova variável chamada dados_ponto_virgula que será igual a pd.read_csv() passando a url_2.

In [6]:
dados_ponto_virgula = pd.read_csv(url_2)

Agora, vamos visualizar as 5 primeiras linhas desse arquivo com a função head().

In [7]:
dados_ponto_virgula.head()

Id;Year_Birth;Education;Marital_Status;Income;Kidhome;Teenhome;Dt_Customer;Recency;MntWines;MntFruits;MntMeatProducts;MntFishProducts;MntSweetProducts;MntGoldProds;NumDealsPurchases;NumWebPurchases;NumCatalogPurchases;NumStorePurchases;NumWebVisitsMonth;Response;Complain
0  1826;1970;Graduation;Divorced;84835;0;0;6/16/2...                                                                                                                                                                                                                             
1  1;1961;Graduation;Single;57091;0;0;6/15/2014;0...                                                                                                                                                                                                                             
2  10476;1958;Graduation;Married;67267;0;1;5/13/2...                                                                                                                                                                                                                             
3  1386;1967;Graduation;Together;32474;1;1;11/5/2...                                                                                                                                                                                                                             
4  5371;1989;Graduation;Single;21474;1;0;8/4/2014...

Ao executar essa célula, aconteceu alguma coisa muito estranha. Note que não temos separação de colunas. Temos as linhas e as informações estão todas juntas, sem espaço. Muito diferente de como visualizamos antes.

O que aconteceu? Como podemos corrigir isso para quando quisermos ler um arquivo .csv separado por ponto e vírgula?

Nós tentamos ler um arquivo CSV separado por ponto e vírgula e o resultado ficou muito esquisito, as informações apareceram bagunçadas. Vamos resolver isso agora, com a ajuda da documentação da biblioteca Pandas.

Na documentação ,consultaremos a parte que fala sobre a função read_csv(). Existem vários parâmetros que podem ser alterados quando queremso fazer a leitura de um CSV.

Recomendo que você leia essa documentação e explore cada parâmetro. Aqui vamos direto ao ponto, que é o parâmetro sep. Esse parâmetro é o que mostra qual será o separador do arquivo CSV. A documentação indica que o default, o padrão dele, é a separação por vírgulas. Então, basta alterarmos esse parâmetro.

De volta ao Colab, vamos adicionar uma nova célula de código e criaremos uma variável chamada dados_sem_vírgula que será igual a pd.read_csv(url_2). Em seguida, adicionaremos o parâmetro sep igual a pornto e vírgula. Assim ele vai entender que o separador é ponto e vírgula. Vamos executar esta célula:

In [8]:
dados_ponto_virgula = pd.read_csv(url_2, sep = ';')

In [9]:
dados_ponto_virgula.head()

Id  Year_Birth   Education Marital_Status   Income  Kidhome  Teenhome  \
0   1826        1970  Graduation       Divorced  84835.0        0         0   
1      1        1961  Graduation         Single  57091.0        0         0   
2  10476        1958  Graduation        Married  67267.0        0         1   
3   1386        1967  Graduation       Together  32474.0        1         1   
4   5371        1989  Graduation         Single  21474.0        1         0   

  Dt_Customer  Recency  MntWines  ...  MntFishProducts  MntSweetProducts  \
0   6/16/2014        0       189  ...              111               189   
1   6/15/2014        0       464  ...                7                 0   
2   5/13/2014        0       134  ...               15                 2   
3   11/5/2014        0        10  ...                0                 0   
4    8/4/2014        0         6  ...               11                 0   

   MntGoldProds  NumDealsPurchases  NumWebPurchases  NumCatalogPurchases  \
0           218                  1                4                    4   
1            37                  1                7                    3   
2            30                  1                3                    2   
3             0                  1                1                    0   
4            34                  2                3                    1   

   NumStorePurchases  NumWebVisitsMonth  Response  Complain  
0                  6                  1         1         0  
1                  7                  5         1         0  
2                  5                  2         0         0  
3                  2                  7         0         0  
4                  2                  7         1         0  

[5 rows x 22 columns]

Agora, dados apareceram corretamente no DataFrame. Então, é importante verificar qual é o separador do seu arquivo CSV e indicar no parâmetro sep caso não seja uma separação por vírgula.

Além desse parâmetro temos vários outros que podem ser explorados. Vamos falar sobre alguns deles.

### ***Parâmetro nrows***

Começarei com um parâmetro que é interessante se você quiser visualizar apenas algumas linhas do seu DataFrame é bom para quando temos um DataFrame muito grande e queremos apenas ter uma visualização geral do conteúdo.

Criaremos uma variável chamada dados_primeiras_linhas e dentro do pd.read_csv() passaremos a variável url e o parâmetro nrows igual à quantidade de linha que quero que sejam monstrada, vou colocar apenas 5.

In [10]:
dados_primeiras_linhas = pd.read_csv(url,nrows=5)

Após executar essa célula, podemos visualizar as cinco linhas que pedimos executando a seguinte célula:

In [11]:
dados_primeiras_linhas

Id  Year_Birth   Education Marital_Status  Income  Kidhome  Teenhome  \
0   1826        1970  Graduation       Divorced   84835        0         0   
1      1        1961  Graduation         Single   57091        0         0   
2  10476        1958  Graduation        Married   67267        0         1   
3   1386        1967  Graduation       Together   32474        1         1   
4   5371        1989  Graduation         Single   21474        1         0   

  Dt_Customer  Recency  MntWines  ...  MntFishProducts  MntSweetProducts  \
0   6/16/2014        0       189  ...              111               189   
1   6/15/2014        0       464  ...                7                 0   
2   5/13/2014        0       134  ...               15                 2   
3   11/5/2014        0        10  ...                0                 0   
4    8/4/2014        0         6  ...               11                 0   

   MntGoldProds  NumDealsPurchases  NumWebPurchases  NumCatalogPurchases  \
0           218                  1                4                    4   
1            37                  1                7                    3   
2            30                  1                3                    2   
3             0                  1                1                    0   
4            34                  2                3                    1   

   NumStorePurchases  NumWebVisitsMonth  Response  Complain  
0                  6                  1         1         0  
1                  7                  5         1         0  
2                  5                  2         0         0  
3                  2                  7         0         0  
4                  2                  7         1         0  

[5 rows x 22 columns]

### ***Parâmetro usecols***

Outro parâmetro que também podemos testar agora é um parâmetro que consegue mostrar apenas algumas colunas.

Por exemplo, vamos supor que queremos visualizar os clientes apenas pelo seu id, ano de nascimento e seu rendimento anual.

Para isso, criaremos uma variável chamada dados_selecao igual a pd.read_csv() passando url e usecols, sinal de igual, e dentor de colchetes vamos informar quais colunas queremos visualizar. Vamos querer as colunas Id, ano de nascimento (Year_Birth) e a coluna do rendimento anual (Income).

In [12]:
dados_selecao = pd.read_csv(url, usecols=['Id', 'Year_Birth', 'Income'])
dados_selecao

Id  Year_Birth   Income
0      1826        1970  84835.0
1         1        1961  57091.0
2     10476        1958  67267.0
3      1386        1967  32474.0
4      5371        1989  21474.0
...     ...         ...      ...
2235  10142        1976  66476.0
2236   5263        1977  31056.0
2237     22        1976  46310.0
2238    528        1978  65819.0
2239   4070        1969  94871.0

[2240 rows x 3 columns]

Outra dica é que essas colunas que selecionamos podem ser indicadas pela posição ao invés do nome. Lembre-se que em Python começamos a indexar em zero, então as posições começam a partir do zero.

Na tabela original, a coluna do Id seria a coluna 0; a coluna Year_Birth é a coluna 1 e a Income é a coluna 4. Usaremos o mesmo código, mas com os valores no lugar nos nomes das colunas.

In [13]:
dados_selecao = pd.read_csv(url, usecols=[0,1,4])
dados_selecao

Id  Year_Birth   Income
0      1826        1970  84835.0
1         1        1961  57091.0
2     10476        1958  67267.0
3      1386        1967  32474.0
4      5371        1989  21474.0
...     ...         ...      ...
2235  10142        1976  66476.0
2236   5263        1977  31056.0
2237     22        1976  46310.0
2238    528        1978  65819.0
2239   4070        1969  94871.0

[2240 rows x 3 columns]

Exploramos alguns parâmetros da função read_csv(), agora chegou um momento muito especial: como escrever no formato CSV usando a biblioteca Pandas? Como salvar um arquivo no formato CSV?

Por exemplo, nós obtivemos um DataFrame com algumas colunas que selecionamos: ID, ano de nascimento e rendimento anual. Que tal salvarmos esse DataFrame?

### ***Função to_csv()***

Para isso vamos colocar o nome do DataFrame, que está na variável dados_selecao e usaremos a função to_csv(), dentro do parênteses colocaremos entre aspas qual será o nome do arquivo seguido do formato do arquivo.


In [14]:
dados_selecao.to_csv('clientes_mercado.csv')

Após executar essa célula, para visualizar o arquivo salvo podemos clicar no ícone "Arquivos" do menu lateral à esquerda. Será aberto um painel que vai exibir a estrutura dos arquivos que estamos salvando.

Ao selecionar um arquivo e clicar em "Mais opções" teremos as opções de:

* Fazer download
* Renomear arquivo
* Excluir arquivo
* Copiar caminho
* Atualizar

Nós vamos escolher a opção "Copiar caminho" para entender como fazer a leitura de um arquivo que está salvo no Colab.

Agora, criaremos uma variável chamada clientes_mercado igual a pd.read_csv(). Dentro do parênteses colocaremos entre aspas o caminho que acabamos de copiar:

In [15]:
clientes_mercado = pd.read_csv('/content/clientes_mercado.csv')
clientes_mercado

Unnamed: 0     Id  Year_Birth   Income
0              0   1826        1970  84835.0
1              1      1        1961  57091.0
2              2  10476        1958  67267.0
3              3   1386        1967  32474.0
4              4   5371        1989  21474.0
...          ...    ...         ...      ...
2235        2235  10142        1976  66476.0
2236        2236   5263        1977  31056.0
2237        2237     22        1976  46310.0
2238        2238    528        1978  65819.0
2239        2239   4070        1969  94871.0

[2240 rows x 4 columns]

Mas agora, aconteceu alguma coisa que causou a duplicação do índice e criou a coluna "Unamed". Será que está faltando adicionar algum parâmetro na hora de criar o arquivo CSV?

Vamos checar na documentação da biblioteca Pandas, na seção do to_csv. Recomendo que você explore e entenda melhor sobre esses parâmetros.

Entre os parâmetro do to_csv, falaremos sobre o parâmetro index, ele tem como default, padrão, a opção true. Ou seja, sempre que não modificarmos esse parâmetro, será adicionada uma nova coluna de index porque o padrão está index=true.

Se mudarmos index para false não teremos a adição dessa coluna. É o que vamos fazer.

In [16]:
dados_selecao.to_csv('dados_mercado.csv', index=False)

Após executar essa célula, podemos abrir o painel de arquivos e copiar o caminho desse arquivo dados_mercado.csv recém-criado. Vamos tentar visualizar esse arquivo:

In [17]:
pd.read_csv('/content/dados_mercado.csv')

Id  Year_Birth   Income
0      1826        1970  84835.0
1         1        1961  57091.0
2     10476        1958  67267.0
3      1386        1967  32474.0
4      5371        1989  21474.0
...     ...         ...      ...
2235  10142        1976  66476.0
2236   5263        1977  31056.0
2237     22        1976  46310.0
2238    528        1978  65819.0
2239   4070        1969  94871.0

[2240 rows x 3 columns]

Agora foi exibido corretamente. Não foi criada uma nova coluna. Então, lembre-se de inserir o parâmetro index=False quando for salvar um arquivo CSV.

# Aula 02

Temos um novo conjunto de dados: um grupo de pesquisa com dados das emissões de gás carbônico (CO2) pelos países ao longo dos anos. Eles querem analisar esses dados com o objetivo de entender os impactos ambientais gerados pelos países e pensar em questões de sustentabilidade. Os dados estão em uma planilha, mas o grupo de pesquisa gostaria de usar a biblioteca Pandas no Colab. Será possível?

No GitHub, temos o arquivo emissoes_CO2.xlsx. Pela extensão .xlsx ao final do nome do arquivo, sabemos que se trata do formato Excel. Ao abri-lo, notaremos que não é possível visualizá-lo no GitHub (como visualizamos o CSV em aulas anteriores). Em vez disso, temos a seguinte mensagem:

Logo acima dessa mensagem, temos o link "View raw" para visualizar os dados brutos. Ao clicar nele, será feito um download. Para conferir esses dados, é necessário ter o Excel instalado no computador ou carregar o arquivo no Google Planilhas.

A seguir, aprenderemos como ler esse arquivo com a biblioteca Pandas. Após conectar o ambiente no Google Colab, vamos começar importando a biblioteca Pandas na primeira célula:

In [18]:
import pandas as pd

Após executar, vamos declarar uma variável chamada url, na segunda célula. Ela armazenará o endereço da planilha, isto é, o link do arquivo no GitHub:

In [19]:
url_1 = 'https://github.com/alura-cursos/Pandas/blob/main/emissoes_CO2.xlsx?raw=True'

Como comentamos, não conseguimos ter acesso ao dado bruto. Então como leremos o arquivo? Depois de .xlsx, colocaremos um símbolo de interrogação e passar o parâmetro raw=True para trazer o arquivo bruto.

Após executar, faremos a leitura do arquivo. Na terceira célula, criaremos uma variável chamada dados_co2. Invocaremos a biblioteca Pandas e usaremos a função read_excel(), responsável por ler arquivos nesse formato. Dentro dos parênteses, passaremos a URL:

In [20]:
dados_co2 = pd.read_excel(url_1)

A execução pode demorar um pouco, porque o arquivo é grande. Na sequência, vamos consultar as cinco primeiras linhas do dataframe gerado, com a função head():

In [21]:
dados_co2.head()

País ISO 3166-1 alpha-3   Ano  Total  Carvão  Oléo  Gás  Cimento  \
0  Afeganistão                AFG  1750    0.0     NaN   NaN  NaN      NaN   
1  Afeganistão                AFG  1751    0.0     NaN   NaN  NaN      NaN   
2  Afeganistão                AFG  1752    0.0     NaN   NaN  NaN      NaN   
3  Afeganistão                AFG  1753    0.0     NaN   NaN  NaN      NaN   
4  Afeganistão                AFG  1754    0.0     NaN   NaN  NaN      NaN   

   Queima  Outro  Per Capita  
0     NaN    NaN         NaN  
1     NaN    NaN         NaN  
2     NaN    NaN         NaN  
3     NaN    NaN         NaN  
4     NaN    NaN         NaN

O retorno será uma tabela com cinco linhas e as colunas com o nome do país, código do país, ano, valor total de emissão de gás carbônico, emissões por tipo (carvão, óleo, fás, cimento, queima, outro) e o valor per capita (por cabeça).

Como comentamos, uma planilha pode ter diferentes páginas. Para descobrir se há mais páginas, usaremos uma classe da biblioteca Pandas chamada ExcelFile(). Entre os parênteses, passaremos a URL. Depois, empregamos o atributo sheet_names (nome das páginas):

In [22]:
pd.ExcelFile(url_1).sheet_names

['emissoes_C02', 'emissoes_percapita', 'fontes']

A execução pode ser um pouco demorada. Como resultado, temos os nomes das três páginas. Para especificar uma página (entre outras ações), podemos explorar alguns parâmetros da função read_excel().

### Parâmetro sheet_name
A seguir, estudaremos o parâmetro sheet_name, com o qual podemos especificar a página da planilha queremos mostrar. Descendo um pouco a página, encontramos uma explicação mais detalhada sobre esse parâmetro.

Por padrão, esse parâmetro é igual a zero. Ou seja, quando não alteramos esse valor, a primeira página será mostrada. Já se definirmos sheet_name=1, consultaremos a segunda página. Alternativamente, podemos escrever o nome da página, por exemplo, sheet_name="Pagina2".

Vamos testar no Colab! Nosso objetivo será ler a segunda página, chamada "emissoes_percapita". Criaremos uma variável chamada percapita e chamaremos a função read_excel() da biblioteca Pandas. Como parâmetros, informaremos a URL e o `sheet_name="emissoes_percapita":

In [23]:
percapita = pd.read_excel(url_1, sheet_name='emissoes_percapita')
percapita.head()

País ISO 3166-1 alpha-3   Ano  Total  Carvão  Óleo  Gás  Cimento  \
0  Afeganistão                AFG  1750    NaN     NaN   NaN  NaN      NaN   
1  Afeganistão                AFG  1751    NaN     NaN   NaN  NaN      NaN   
2  Afeganistão                AFG  1752    NaN     NaN   NaN  NaN      NaN   
3  Afeganistão                AFG  1753    NaN     NaN   NaN  NaN      NaN   
4  Afeganistão                AFG  1754    NaN     NaN   NaN  NaN      NaN   

   Queima  Outro  
0     NaN    NaN  
1     NaN    NaN  
2     NaN    NaN  
3     NaN    NaN  
4     NaN    NaN

Agora, temos um dataframe contendo somente valores per capita para cada um dos países. Conseguimos ler uma página específica da planilha.

Vamos repetir o processo para a terceira página, chamada "fontes":

In [24]:
fontes = pd.read_excel(url_1, sheet_name='fontes')
fontes.head()

País ISO 3166-1 alpha-3   Ano   Total  Carvão    Oléo     Gás  \
0  Afeganistão                AFG  1750  [NONE]  [NONE]  [NONE]  [NONE]   
1  Afeganistão                AFG  1751  [NONE]  [NONE]  [NONE]  [NONE]   
2  Afeganistão                AFG  1752  [NONE]  [NONE]  [NONE]  [NONE]   
3  Afeganistão                AFG  1753  [NONE]  [NONE]  [NONE]  [NONE]   
4  Afeganistão                AFG  1754  [NONE]  [NONE]  [NONE]  [NONE]   

  Cimento  Queima   Outro Per Capita  
0  [NONE]  [NONE]  [NONE]     [NONE]  
1  [NONE]  [NONE]  [NONE]     [NONE]  
2  [NONE]  [NONE]  [NONE]     [NONE]  
3  [NONE]  [NONE]  [NONE]     [NONE]  
4  [NONE]  [NONE]  [NONE]     [NONE]

O retorno será um dataframe com as fontes de onde os dados foram obtidos. Empregando o parâmetro sheet_name, conseguimos fazer o carregamento de diferentes páginas da planilha.

### Parâmetro usecols
Entre outros parâmetros da função read_excel(), existe o usecols, com o qual especificamos as colunas que queremos mostrar. Vamos explorá-lo, a seguir.

Criaremos uma variável chamada intevalo e chamaremos a função read_excel() da biblioteca Pandas. No primeiro parâmetro, passaremos a URL. No segundo, definiremos o nome da página, sheet_name='emissoes_C02'. No terceiro, indicaremos o intervalo desejado, com usecols= 'A:D'. Como aprendemos anteriormente, as colunas são nomeadas por letras. Ao indicar A:D, selecionamos o intervalo da coluna A até a coluna D:

In [25]:
intervalo = pd.read_excel(url_1, sheet_name='emissoes_C02', usecols= 'A:D')
intervalo

País ISO 3166-1 alpha-3   Ano         Total
0      Afeganistão                AFG  1750  0.000000e+00
1      Afeganistão                AFG  1751  0.000000e+00
2      Afeganistão                AFG  1752  0.000000e+00
3      Afeganistão                AFG  1753  0.000000e+00
4      Afeganistão                AFG  1754  0.000000e+00
...            ...                ...   ...           ...
63099       Global                WLD  2017  3.609674e+10
63100       Global                WLD  2018  3.682651e+10
63101       Global                WLD  2019  3.708256e+10
63102       Global                WLD  2020  3.526409e+10
63103       Global                WLD  2021  3.712385e+10

[63104 rows x 4 columns]

Agora, temos um dataframe com 63104 linhas (rows) e apenas 4 colunas (coluns). Ou seja, selecionamos apenas o intervalo com nossas colunas de interesse: o nome do país, o código do país, o ano e o valor total de emissão de gás carbônico.

Definir as colunas é especialmente útil quando temos uma página com mais de uma tabela. Assim, conseguimos selecionar somente o intervalo desejado.

### Parâmetro nrows
Outro parâmetro da função read_excel() é o nrows, responsável por definir a quantidade a linhas exibidas. Para demonstrá-lo, vamos criar uma variável chamada intervalo_2 e chamar read_excel(). Além da URL, do nome da página e do intervalo de colunas, definiremos a exibição de apenas 10 linhas com nrows=10:

In [26]:
intervalo_2 = pd.read_excel(url_1, sheet_name='emissoes_C02', usecols= 'A:D', nrows=10)
intervalo_2

País ISO 3166-1 alpha-3   Ano  Total
0  Afeganistão                AFG  1750      0
1  Afeganistão                AFG  1751      0
2  Afeganistão                AFG  1752      0
3  Afeganistão                AFG  1753      0
4  Afeganistão                AFG  1754      0
5  Afeganistão                AFG  1755      0
6  Afeganistão                AFG  1756      0
7  Afeganistão                AFG  1757      0
8  Afeganistão                AFG  1758      0
9  Afeganistão                AFG  1759      0

### Salvando em formato Excel
Anteriormente, consultamos as cinco primeiras linhas do dataframe com os dados per capita com o seguinte comando:

In [27]:
percapita.head()

País ISO 3166-1 alpha-3   Ano  Total  Carvão  Óleo  Gás  Cimento  \
0  Afeganistão                AFG  1750    NaN     NaN   NaN  NaN      NaN   
1  Afeganistão                AFG  1751    NaN     NaN   NaN  NaN      NaN   
2  Afeganistão                AFG  1752    NaN     NaN   NaN  NaN      NaN   
3  Afeganistão                AFG  1753    NaN     NaN   NaN  NaN      NaN   
4  Afeganistão                AFG  1754    NaN     NaN   NaN  NaN      NaN   

   Queima  Outro  
0     NaN    NaN  
1     NaN    NaN  
2     NaN    NaN  
3     NaN    NaN  
4     NaN    NaN

Nosso grupo de pesquisa deseja analisar somente os valores per capita, então vamos salvá-los esse arquivo em formato Excel para mantê-los separados.

Em uma nova célula no Colab, vamos usar o nome do dataframe "percapita" e usar a função to_excel() para realizar a escrita no formato Excel. Dentro dos parênteses, passaremos dois parâmetros. O primeiro será o nome do arquivo que queremos salvar, no caso, co2_percapita.xlsx. O segundo parâmetro será o index, que estudamos anteriormente. No caso, o deixaremos com valor False:

In [28]:
percapita.to_excel('co2_percapita.xlsx', index=False)

Após executar a célula, vamos checar onde o arquivo foi salvo. No menu à esquerda, acessaremos na aba "Arquivos" e encontraremos o arquivo co2_percapita.xlsx. Para fazer a leitura e conferir se deu tudo certo, vamos copiar o seu caminho. Basta clicar nos três pontos no canto direito do nome do arquivo e selecionar "Copiar caminho".

Em uma nova célula, usaremos a função read_excel() e passar o endereço do arquivo:

In [29]:
pd.read_excel('/content/co2_percapita.xlsx')

País ISO 3166-1 alpha-3   Ano      Total     Carvão       Óleo  \
0      Afeganistão                AFG  1750        NaN        NaN        NaN   
1      Afeganistão                AFG  1751        NaN        NaN        NaN   
2      Afeganistão                AFG  1752        NaN        NaN        NaN   
3      Afeganistão                AFG  1753        NaN        NaN        NaN   
4      Afeganistão                AFG  1754        NaN        NaN        NaN   
...            ...                ...   ...        ...        ...        ...   
63099       Global                WLD  2017  4749682.0  1908857.0  1610910.0   
63100       Global                WLD  2018  4792753.0  1919213.0  1596350.0   
63101       Global                WLD  2019  4775633.0  1896468.0  1589920.0   
63102       Global                WLD  2020  4497423.0  1807760.0  1427353.0   
63103       Global                WLD  2021  4693699.0  1893923.0  1496614.0   

             Gás   Cimento   Queima    Outro  
0            NaN       NaN      NaN      NaN  
1            NaN       NaN      NaN      NaN  
2            NaN       NaN      NaN      NaN  
3            NaN       NaN      NaN      NaN  
4            NaN       NaN      NaN      NaN  
...          ...       ...      ...      ...  
63099   940144.0  198416.0  51579.0  39776.0  
63100   979965.0  204225.0  53634.0  39366.0  
63101   984878.0  208309.0  56569.0  39490.0  
63102   963695.0  208844.0  51981.0  37789.0  
63103  1001585.0  211472.0  52663.0  37443.0  

[63104 rows x 10 columns]

Temos um dataframe contendo os dados per capita que acabaram de ser salvos. Temos 630104 linhas e 10 colunas. Conseguimos salvar o arquivo!

No Google Planilhas, é possível obter o link da planilha e compartilhá-lo com outras pessoas. Além disso, podemos usar esse link para acessar a planilha no Colab!

Ao clicar no botão "Compartilhar" no canto superior direito, será aberta uma caixa de diálogo no centro da tela. No tópico "Acesso geral", selecionaremos a opção "Qualquer pessoa com o link". Em seguida, clicaremos em "Copiar link" no canto inferior esquerdo, depois em "Concluído" no canto inferior direito.

No Colab, vamos colar o endereço em uma nova célula. No caso, trata-se da seguinte URL:

https://docs.google.com/spreadsheets/d/1MKTXZwQ8g7exXR26VowD8NMkPpXONRm2qTpHPJ5YBy4/edit?usp=sharing

Toda planilha possui um ID para identificá-la. Este ID está presente nessa URL, entre /d/ e /edit?usp=sharing. No caso, o ID da planilha é o seguinte.

Em uma nova célula, criaremos uma variável chamada sheet_id para armazenar esse ID.

In [30]:
sheet_id = '1MKTXZwQ8g7exXR26VowD8NMkPpXONRm2qTpHPJ5YBy4'

Para acessar a planilha no Colab, precisaremos alterar alguns trechos da URL. Em uma nova célula, criaremos uma variável chamada url, cujo valor inicial será a URL de compartilhamento até o /d/.
Após /d/, vamos inserir a variável sheet_id entre chaves.

Para acessar a variável sheet_id nessa URL, empregaremos uma f-string, uma maneira interessante de formatar strings em Python. Basta envolver a URL entre aspas simples e incluir a letra "f" no início.

Assim, todos os elementos que aparecem entre chaves serão substituídos pelas variáveis correspondentes. No caso, o trecho {sheet_id} da URL será substituído pela string que armazenamos na variável sheet_id anteriormente. Essa prática torna o código mais simples, melhorando sua escrita e a leitura.

A seguir, adicionaremos alguns parâmetros para permitir o acesso à planilha. Vamos colocar uma barra após {sheet_id} e inserir o parâmetro gviz/tq:

O que é esse parâmetro e para que ele serve? Para ter acesso à planilha, é necessário acessar a API de visualização de dados do Google. API significa Application Programming Interface, isto é, uma interface de programação de aplicações. Elas permitem sistemas diferentes se comuniquem.

No caso, queremos criar a comunicação entre o Google Colab e o Google Planilhas. O parâmetro gviz/tq permite o acesso à API responsável por essa comunicação.

Após gviz/tq, adicionaremos um ponto de interrogação e o parâmetro tqx=out:csv:


In [31]:
url_2 = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet'

Assim, todos os dados da planilha serão retornados, incluindo cabeçalho, linhas e colunas. Nossa URL está pronta! A seguir, vamos verificar se tudo funciona como esperado.

Em uma nova célula, criaremos uma variável chamada dados_co2_sheets. Como definimos que o retorno será em formato CSV, chamaremos a função read_csv() da biblioteca Pandas. Como parâmetro, passaremos a variável url:

In [32]:
dados_co2_sheets = pd.read_csv(url_2)
dados_co2_sheets.head()

País ISO 3166-1 alpha-3   Ano Total Carvão Oléo  Gás Cimento Queima  \
0  Afeganistão                AFG  1750     0    NaN  NaN  NaN     NaN    NaN   
1  Afeganistão                AFG  1751     0    NaN  NaN  NaN     NaN    NaN   
2  Afeganistão                AFG  1752     0    NaN  NaN  NaN     NaN    NaN   
3  Afeganistão                AFG  1753     0    NaN  NaN  NaN     NaN    NaN   
4  Afeganistão                AFG  1754     0    NaN  NaN  NaN     NaN    NaN   

  Outro Per Capita  
0   NaN        NaN  
1   NaN        NaN  
2   NaN        NaN  
3   NaN        NaN  
4   NaN        NaN

Retornando outras páginas
Verificamos anteriormente que já três páginas diferentes em nossa planilha, recapitulando:

emissoes_CO2
emissoes_percapita
fontes
Quando trabalhamos com read_excel(), adicionamos parâmetros na função para especificar a página desejada. A seguir, vamos aprender como realizar essa especificação para o Google Planilhas.

Em uma nova célula, definiremos sheet_id com o ID da planilha (que permanece o mesmo).

Depois, criaremos uma variável chamada sheet_name. Com o objetivo de acessar a segunda página, armazenaremos a string "emissoes_percapita":

Em seguida, vamos declarar a url_percapita, que será igual à f-string que usamos anteriormente. Ela já contém o endereço correto com a variável sheet_id.

Para especificar a página da planilha que queremos acessar, basta inserir um símbolo de igual ao final da URL, seguida da variável sheet_name entre chaves.

In [33]:
sheet_id = '1MKTXZwQ8g7exXR26VowD8NMkPpXONRm2qTpHPJ5YBy4'
sheet_name = 'emissoes_percapita'
url_percapita = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}'

Dessa forma, temos acesso ao ID da planilha e ao nome da página desejada.

Após executar a célula, criaremos uma variável chamada per_capita_sheets para conferir o dataframe com os dados per capita. Vamos chamar a função read_csv() do Pandas e passamos a URL como parâmetro:

In [34]:
percapita_sheets = pd.read_csv(url_percapita)
percapita_sheets.head()

País ISO 3166-1 alpha-3   Ano Total Carvão Óleo  Gás Cimento Queima  \
0  Afeganistão                AFG  1750   NaN    NaN  NaN  NaN     NaN    NaN   
1  Afeganistão                AFG  1751   NaN    NaN  NaN  NaN     NaN    NaN   
2  Afeganistão                AFG  1752   NaN    NaN  NaN  NaN     NaN    NaN   
3  Afeganistão                AFG  1753   NaN    NaN  NaN  NaN     NaN    NaN   
4  Afeganistão                AFG  1754   NaN    NaN  NaN  NaN     NaN    NaN   

   Outro  
0    NaN  
1    NaN  
2    NaN  
3    NaN  
4    NaN

Temos o resultado esperado! Para finalizar, podemos repetir o processo com a última página da planilha, cujo nome é "fontes". Podemos copiar a célula em que definimos o ID da planilha, o nome da página e a URL, fazendo as adaptações necessárias. Basta trocar o nome de "emissoes_percapita" para "fontes" e alterar o nome da variável de "url_percapita" para "url_fontes":

In [35]:
sheet_id = '1MKTXZwQ8g7exXR26VowD8NMkPpXONRm2qTpHPJ5YBy4'
sheet_name = 'fontes'
url_fontes = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}'

Após executar a célula, criaremos a variável fontes_sheets e chamaremos a função read_csv(), passando url_fontes como parâmetro:

In [36]:
fontes_sheets = pd.read_csv(url_fontes)
fontes_sheets.head()

País ISO 3166-1 alpha-3   Ano   Total  Carvão    Oléo     Gás  \
0  Afeganistão                AFG  1750  [NONE]  [NONE]  [NONE]  [NONE]   
1  Afeganistão                AFG  1751  [NONE]  [NONE]  [NONE]  [NONE]   
2  Afeganistão                AFG  1752  [NONE]  [NONE]  [NONE]  [NONE]   
3  Afeganistão                AFG  1753  [NONE]  [NONE]  [NONE]  [NONE]   
4  Afeganistão                AFG  1754  [NONE]  [NONE]  [NONE]  [NONE]   

  Cimento  Queima   Outro Per Capita  
0  [NONE]  [NONE]  [NONE]     [NONE]  
1  [NONE]  [NONE]  [NONE]     [NONE]  
2  [NONE]  [NONE]  [NONE]     [NONE]  
3  [NONE]  [NONE]  [NONE]     [NONE]  
4  [NONE]  [NONE]  [NONE]     [NONE]

# Aula 03

Agora, temos um hospital que deseja acessar os dados de pacientes, mas os arquivos estão todos no formato JSON. Dessa forma, é difícil extrair informações relevantes a partir dos dados. O nosso objetivo será usar a biblioteca Pandas para ler e manipular esses arquivos.

### O que é um arquivo JSON?
A seguir, temos um exemplo de informações de um arquivo JSON com dados de uma paciente do hospital:

In [37]:
{"ID":"01", "Faixa_etaria":"55-59", "Sexo_biologico":"Feminino"}

{'ID': '01', 'Faixa_etaria': '55-59', 'Sexo_biologico': 'Feminino'}

Neste arquivo, temos três informações a respeito da pessoa:

Um ID atribuído a ela ("ID");
Sua faixa etária ("Faixa_etaria");
Seu sexo biológico ("Sexo_biologico").
Estas informações são o que chamamos de chaves. Uma chave é o que indexa, ou seja, posiciona um elemento dentro do arquivo JSON. Cada chave é acompanhada de seus respectivos valores.

Desse modo, o ID da paciente carrega o valor "01", enquanto a sua faixa etária corresponde à faixa entre 55 e 59 anos ("55-59") e o sexo biológico foi atribuído como "Feminino".

Os valores de cada chave podem ser números do tipo inteiro (int) ou float, podem ser caracteres de texto (string) ou uma lista com vários elementos.

Assim, um arquivo JSON é formado por chaves e seus respectivos valores. Sempre haverá o símbolo de abrir e fechar chaves no começo e no fim das informações. Nesse sentido, o arquivo se assemelha muito a um dicionário em Python.

Lembrando que, após a chave, teremos dois pontos e o valor correspondente, seguidos de uma vírgula quando houver mais informações.

### O que significa JSON?
JSON é uma sigla em inglês para JavaScript Object Notation. Em português, são os Objetos de Notação JavaScript. Este é um formato de texto leve baseado em um subconjunto da linguagem de programação JavaScript. Ele é muito utilizado em APIs também.

Até aqui, já entendemos o que é um arquivo JSON e como ele é estruturado. Que tal carregarmos os dados do hospital no Google Colab?

### Manipulando os dados do hospital
Com o Google Colab aberto, clicaremos no botão "+ Código" (ou "+ Code") no canto superior esquerdo da tela para abrir uma nova célula de código.

Começaremos importando a Biblioteca Pandas digitando import pandas as pd. Em seguida, pressionaremos a o atalho "Shift + Enter" para executar a célula.

Os dados a serem carregados estão no meu computador. Farei a importação deles para o Google Colab. No menu esquerdo, selecionarei o ícone de uma pasta, que corresponde à opção "Arquivos".

Uma nova aba surgirá no canto esquerdo da tela. Clicaremos em um ícone de uma folha de papel com uma seta para cima, o botão "Fazer upload para o armazenamento da sessão". Isso abrirá o gerenciador de arquivos do computador. Escolherei o arquivo "pacientes", no formato JSON, e clicarei em "Abrir".

Assim que o upload for finalizado, veremos o nome do arquivo no canto esquerdo da tela. Clicaremos nos três pontos na vertical que estão ao lado do nome do arquivo e selecionaremos a opção "Copiar caminho".

Em seguida, fecharemos o menu na lateral esquerda para expandir a tela de edição do código. Para começar, criaremos uma variável chamada dados_pacientes. Ela será igual a pd.read_json. Esta é a função responsável por fazer a leitura dos arquivos em formato JSON.

Abriremos parênteses e aspas simples imediatamente após o nome da função e colaremos o caminho copiado do projeto dentro das aspas. O resultado é o seguinte:

In [38]:
import pandas as pd

In [39]:
dados_paciente = pd.read_json('/content/pacientes.json')

In [40]:
dados_paciente

ID_paciente Doenca_cardiaca    IMC Fumante Consumo_alcool  AVC  \
0              0             Nao  16.60     Sim            Nao  Nao   
1              1             Nao  20.34     Nao            Nao  Sim   
2              2             Nao  26.58     Sim            Nao  Nao   
3              3             Nao  24.21     Nao            Nao  Nao   
4              4             Nao  23.71     Nao            Nao  Nao   
..           ...             ...    ...     ...            ...  ...   
995          995             Nao  28.29     Sim            Nao  Nao   
996          996             Nao  25.69     Sim            Nao  Nao   
997          997             Sim  26.99     Nao            Nao  Nao   
998          998             Nao  44.29     Nao            Nao  Nao   
999          999             Nao  25.83     Nao            Nao  Nao   

     Saude_fisica  Saude_mental Dificuldade_caminhar Sexo_biologico  \
0               3            30                  Nao       Feminino   
1               0             0                  Nao       Feminino   
2              20            30                  Nao      Masculino   
3               0             0                  Nao       Feminino   
4              28             0                  Sim       Feminino   
..            ...           ...                  ...            ...   
995            10            20                  Nao       Feminino   
996             0             0                  Nao       Feminino   
997             1             0                  Nao      Masculino   
998            30             0                  Sim       Feminino   
999             0             0                  Nao      Masculino   

    Faixa_etaria    Raca Diabetes Atividade_fisica Saude_geral  Horas_sono  \
0          55-59  Branca      Sim              Sim   Muito boa           5   
1        80 ou +  Branca      Nao              Sim   Muito boa           7   
2          65-69  Branca      Sim              Sim    Razoavel           8   
3          75-79  Branca      Nao               No         Boa           6   
4          40-44  Branca      Nao              Sim   Muito boa           8   
..           ...     ...      ...              ...         ...         ...   
995        65-69   Preta      Sim              Sim    Razoavel           8   
996        75-79  Branca      Nao              Sim   Excelente           8   
997        70-74  Branca      Nao              Sim   Muito boa           8   
998        70-74  Branca      Sim               No         Boa           6   
999        70-74   Preta      Sim               No   Excelente           7   

    Asma Doenca_renal Cancer_pele  
0    Sim          Nao         Sim  
1    Nao          Nao         Nao  
2    Sim          Nao         Nao  
3    Nao          Nao         Sim  
4    Nao          Nao         Nao  
..   ...          ...         ...  
995  Nao          Nao         Nao  
996  Nao          Nao         Nao  
997  Nao          Nao         Nao  
998  Sim          Nao         Nao  
999  Nao          Nao         Nao  

[1000 rows x 19 columns]

Executaremos esta célula pressionando "Shift + Enter" e, em seguida, escreveremos dados_pacientes para visualizar o dataframe, pressionando "Shift + Enter" em seguida para executar a célula.

O data frame é composto por mil linhas e 19 colunas com informações de pacientes. Alguns dados disponíveis são:

ID de paciente;
Se a pessoa tem alguma doença cardíaca;
O seu IMC;
Se é fumante;
Se consome álcool;
Faixa etária;
Raça/etnia.
Além destas, existe uma série de outras informações sobre a saúde física e mental de cada paciente.

Deu tudo certo com o arquivo de pacientes, mas nem sempre é tão simples fazer a leitura de um arquivo JSON. Algumas vezes, as informações podem estar aninhadas dentro do arquivo JSON.

Mas o que seriam informações aninhadas? Para entendermos isso melhor, carregaremos outro arquivo usando o mesmo caminho: clicaremos no ícone da pasta no canto esquerdo da tela e depois no ícone de folha de papel com uma seta para cima. Escolheremos o arquivo chamado "pacientes_2".

Feito o upload, clicaremos nos três pontos e selecionaremos "Copiar caminho". Em seguida, clicaremos uma nova variável chamada dados_pacientes_2, que será igual a pd.read_json('/content/pacientes_2.json'), o que corresponde ao caminho para o arquivo.

In [41]:
dados_pacientes_2 = pd.read_json('/content/pacientes_2.json')
dados_pacientes_2

Pesquisa   Ano  \
0  Principais Indicadores de Doenca Cardiaca  2020   
1  Principais Indicadores de Doenca Cardiaca  2020   
2  Principais Indicadores de Doenca Cardiaca  2020   

                                           Pacientes  
0  {'ID': '01', 'Faixa_etaria': '55-59', 'Sexo_bi...  
1  {'ID': '02', 'Faixa_etaria': '80 ou +', 'Sexo_...  
2  {'ID': '03', 'Faixa_etaria': '65-69', 'Sexo_bi...

Executaremos o código e, em seguida, verificaremos o seu conteúdo escrevendo dados_pacientes_2 e executaremos esta célula.

O resultado é uma tabela com três colunas. A primeira coluna, intitulada "Pesquisa", tem as mesmas informações em todas as linhas, ou seja, o texto "Principais Indicadores de Doença Cardíaca". A segunda coluna exibe o ano em que a pesquisa foi feita e a última coluna, chamada "Pacientes", agrupou todas as informações de cada paciente em uma única célula.

Com isso, não conseguimos obter a separação de cada dado, tampouco ler todas as informações disponíveis, uma vez que o conteúdo da célula está cortado (conseguimos ver o ID e a faixa etária).

Este é um caso típico de informações aninhadas. Não há separação das colunas e das linhas de maneira a facilitar a leitura e a manipulação dos dados.

Anteriormente, tentamos fazer a leitura de um arquivo JSON com informações aninhadas na coluna "Paciente". Antes de normalizar os dados desta coluna, vamos entender a estrutura do arquivo JSON.

Para isso, abriremos o editor de textos em JSON jsoncrack.com no navegador. Selecionaremos a opção "Go to editor", no centro da tela.

Seremos redirecionados a uma nova janela com o editor de texto JSON. Na lateral esquerda, selecionaremos a primeira opção, representada por um ícone de folha de papel com a ponta dobrada ("Import File"). Uma nova aba surgirá na tela e clicaremos na opção "Click Here to Upload JSON".

Em seguida, escolheremos o arquivo "pacientes_2", clicaremos em "Abrir" e depois em "Import". O arquivo JSON carregará no editor. Do lado direito, visualizaremos a estrutura do arquivo em código. Porém, o lado direito exibe uma estrutura em forma de fluxograma.

Se ampliarmos a estrutura, perceberemos há um primeiro quadrado indicando que se trata de uma pesquisa chamada "Principais Indicadores de Doença Cardíaca" feita no ano de 2020.

Neste ano, a pesquisa dispunha de informações de três pacientes (próximo item no fluxograma). Esse item se conecta a três caixas de texto, com as informações de cada paciente. Se ampliarmos uma das caixas, observaremos as seguintes informações dispostas em sequência:

* ID;
* Faixa etária;
* Sexo biológico;
* Raça;
* IMC;
* Se é fumante ou não;
* Se consome álcool;
* Indicador de saúde física;
* Indicador de saúde mental;
* Se ela tem dificuldade para caminhar;
* Se pratica atividade física;
* Seu estado de saúde geral;
* Média de horas de sono por dia.

Para cada pessoa, há uma lista com os problemas de saúde. Por exemplo, a pessoa com o ID "01" tem diabetes, asma e câncer de pele.

Isso nos mostra a estrutura completa do arquivo. Sabendo disso, queremos obter as informações das pessoas, ou seja, de cada paciente.

Para normalizar esses dados, voltaremos ao Google Colab e criaremos uma variável chamada df_normalizado. Ela será igual pd., seguida de uma função que normaliza os dados em formato JSON (json_normalize()). Dentro dos parênteses da função, passaremos o data frame que desejamos normalizar (dados_pacientes_2).

Em seguida, abriremos colchetes ([]) e, dentro deles, abriremos aspas simples, para indicar qual coluna deve ser normalizada, Pacientes.

In [42]:
df_normalizado = pd.json_normalize(dados_pacientes_2['Pacientes'])
df_normalizado

ID Faixa_etaria Sexo_biologico    Raça    IMC Fumante Consumo_alcool  \
0  01        55-59       Feminino  Branca  16.60     Sim            Nao   
1  02      80 ou +       Feminino  Branca  20.34     Nao            Nao   
2  03        65-69      Masculino  Branca  26.58     Sim            Nao   

   Saude_fisica  Saude_mental Dificuldade_caminhar Atividade_fisica  \
0             3            30                  Nao              Sim   
1             0             0                  Nao              Sim   
2            20            30                  Nao              Sim   

  Saude_geral  Horas_sono                Problemas_saude  
0   Muito boa           5  [Diabetes, Asma, Cancer_pele]  
1   Muito boa           7                          [AVC]  
2   Muito boa           8               [diabetes, Asma]

Executaremos esta célula pressionando "Shift + Enter" e digitaremos df_normalizado para visualizar o novo data frame. Executaremos a célula df_normalizado, que exibirá uma tela diferente.

Agora, conseguimos obter o data frame normalizado, com uma coluna para cada informação. É isso que a função json_normalize faz: transforma tudo o que estiver aninhado em uma única célula em diferentes linhas e colunas.

E agora, como escrevemos no formato JSON?

Já conseguimos normalizar o nosso arquivo JSON, mas e se quisermos salvar o arquivo normalizado?

Para fazer isso, chamaremos o data frame normalizado digitando df_normalizado. Para salvá-lo em formato JSON, usaremos a função .to_json(). Dentro dos parênteses, inseriremos aspas simples e daremos um nome para o arquivo, já indicando o formato em que ele será salvo (historico_pacientes_normalizado.json).

In [43]:
df_normalizado.to_json('historico_pacientes_normalizado.json')

Executaremos esta célula e, se abrirmos novamente o ícone de pasta do lado esquerdo (pasta "Arquivos"), observaremos o arquivo "historico_pacientes_normalizado" em meio à lista de arquivos abertos. Clicando no ícone de três pontos, é possível fazer download, renomear o arquivo, exclui-lo, copiar o caminho ou atualizá-lo.

Clicaremos em "Copiar caminho" e fecharemos a aba esquerda. Para fazer a leitura do arquivo que acabamos de salvar, escreveremos pd.read_json('/content/historico_pacientes_normalizado.json'). Ao executar esta célula, obteremos o data frame normalizado.

Aqui vai uma dica importante: salvamos o arquivo em formato JSON, mas você também pode salvar o seu arquivo em formato CSV ou EXEL, podendo usá-los para facilitar análises futuras. Assim, você não precisará 'salvar ou converter o mesmo arquivo várias vezes.

Mas e se quisermos ler e escrever em outros formatos como o HTML e o XML?

In [44]:
pd.read_json('/content/historico_pacientes_normalizado.json')

ID Faixa_etaria Sexo_biologico    Raça    IMC Fumante Consumo_alcool  \
0   1        55-59       Feminino  Branca  16.60     Sim            Nao   
1   2      80 ou +       Feminino  Branca  20.34     Nao            Nao   
2   3        65-69      Masculino  Branca  26.58     Sim            Nao   

   Saude_fisica  Saude_mental Dificuldade_caminhar Atividade_fisica  \
0             3            30                  Nao              Sim   
1             0             0                  Nao              Sim   
2            20            30                  Nao              Sim   

  Saude_geral  Horas_sono                Problemas_saude  
0   Muito boa           5  [Diabetes, Asma, Cancer_pele]  
1   Muito boa           7                          [AVC]  
2   Muito boa           8               [diabetes, Asma]

# Aula 04

### Projeto
Uma pessoa está criando um sistema de recomendação de filmes. Mas, para isso, ela precisa de dados de filmes, de avaliações que as pessoas deram para eles.

Ela encontrou um artigo web sobre os 100 melhores filmes listados pelo Instituto Americano de Cinema. Esse artigo está na Wikipedia e, na lateral direita da página, temos uma tabela contendo outros artigos criados pelo mesmo instituto, de 1998 a 2008. Há uma versão atualizada de 2007 do nosso artigo em questão, mas verificaremos a de 1988 primeiro.

Descendo a página, encontramos uma tabela interessante para o projeto, contendo as seguintes colunas: nome do filme, ano de lançamento, diretor, produtora e a posição no ranking, indo do primeiro ao centésimo lugar.

Por fim, mais abaixo na página, encontramos um quadro que parece uma tabela contendo apenas os nomes dos filmes, sua posição no ranking e seus respectivos links para a página da Wikipedia, onde podemos checar a sinopse e conhecer mais sobre eles.

Queremos obter a segunda tabela. Mas, antes disso, precisamos confirmar se isso é realmente uma tabela. Como fazer isso numa página web?

### Checando a tabela
Clicando em qualquer lugar da tela com o botão direito do mouse, clicamos na opção "Inspecionar", para inspecionar a página. Com isso, uma nova aba se abrirá à direita da tela, exibindo o conteúdo da página em HTML.

Ou seja, acessamos todos os códigos usados por trás da página, onde podemos inclusive pesquisar o que quisermos. Pressionando "Ctrl + F" no teclado, surgirá uma pequena caixa de busca sobre o segundo menu de opções da aba, em que digitamos o que queremos localizar.

Geralmente, quando temos tabelas em uma página, elas possuem uma tag em HTML chamada "table", que significa "tabela" em inglês. Uma tag é sempre composta por um sinal de menor e maior com a palavra no meio, então digitamos <table> na caixa de busca.

Fazendo isso, localizamos as tabelas no código da página. A caixa de busca indica que há três ocorrências dessa tag no código, e podemos navegar por elas pelas setas à direita da caixa.

A primeira é a tabela de artigos sobre a qual falamos primeiro. Clicamos na seta para baixo para localizar a segunda tabela, de nosso interesse. A terceira é aquela estrutura que parecia uma tabela, e agora sabemos que é uma tabela de fato.

E agora, como podemos carregar esses dados utilizando a biblioteca Pandas?

Para começar, fechamos a aba de inspeção da página. Salvamos essa página em HTML para que você possa acompanhar a aula com o mesmo material do vídeo, porque pode ser que essa página sofra alguma atualização no futuro. Vamos carregá-la no Google Colab.

### Importações
Vamos importar a biblioteca Pandas no Colab, digitando e executando:

In [45]:
import pandas as pd

Agora, importamos a página HTML. No menu lateral esquerdo, clicamos em "Arquivos" (ícone de pasta). Na aba de Arquivos, clicamos em "Fazer upload" (ícone de documento com um "+") na barra superior. Selecionamos o arquivo filmes_wikipedia e clicamos em "Abrir", e depois em "Ok" no aviso do Colab. Um novo item chamado filmes_wikipedia.html surgirá no menu de Arquivos.

Agora, copiamos o caminho desse arquivo. Para isso, clicamos nos três pontos verticais à direita do item filmes_wikipedia.html e, em seguida, em "Copiar caminho". Já podemos fechar o menu de Arquivos.

### Variável dados_html
Na segunda célula, vamos criar uma variável chamada dados_html. Ela receberá o chamado de Pandas, com pd, e a função de leitura de arquivos HTML: .read_html(). Entre os parênteses colocamos aspas simples e colamos o caminho que acabamos de copiar:

In [46]:
dados_html = pd.read_html('/content/filmes_wikipedia.html')
dados_html

[                                                    0  \
 0                                                1998   
 1                                                1999   
 2                                                2000   
 3                                                2001   
 4                                                2002   
 5                                                2003   
 6                                                2004   
 7                                                2005   
 8                                                2005   
 9                                                2006   
 10                                               2006   
 11                                               2007   
 12                                               2008   
 13  .mw-parser-output .hlist dl,.mw-parser-output ...   
 
                                                     1  
 0                                          100 Movies  
 1            

Ao executar essa célula, não recebemos um dataframe. Vamos entender esse resultado.

Aparentemente é uma lista, porque começa com colchetes. Primeiro temos os dados daquela primeira tabela, começando em 1998 e indo até 2008. Abaixo disso, temos os dados da segunda tabela e, por fim, os dados da terceira.

### Mas, por que não surgiu um dataframe?

A função read_html() busca pelas tags <table> e transforma esses dataframes em uma lista. Ou seja, nossa lista contém os dataframes um abaixo do outro. Podemos confirmar isso ao verificar o tipo da variável criada, dados_html, executando o seguinte comando:

In [47]:
type(dados_html)

list

O retorno disso será "list". Podemos até perguntar quantos elementos temos nessa lista, usando a função len(), passando dados_html:

In [48]:
len(dados_html)

3

O retorno desse comando será "3". Como já comentamos, temos três tabelas nessa página. Então, são três dataframes na lista.

### Acessando um dataframe específico
Se quisermos acessar um dataframe específico entre esses três, podemos simplesmente usar sua posição na lista. Então, para visualizar o segundo dataframe, que contém os dados de nosso interesse, vamos criar uma nova variável.

Chamaremos essa nova variável de top_filmes, ou seja, os melhores filmes. Nela vamos chamar dados_html e, entre colchetes, passamos a posição desejada desse dataframe, que será o número 1.

Lembre-se que, em Python, a indexação sempre começa em zero. Então, o primeiro item é o número zero, o segundo é o número um, e o terceiro será o número dois.

Então executamos:

In [49]:
top_filmes = dados_html[1]
top_filmes

Film  Release year              Director  \
0                   Citizen Kane          1941          Orson Welles   
1                     Casablanca          1942        Michael Curtiz   
2                  The Godfather          1972  Francis Ford Coppola   
3             Gone with the Wind          1939        Victor Fleming   
4             Lawrence of Arabia          1962            David Lean   
..                           ...           ...                   ...   
95                 The Searchers          1956             John Ford   
96              Bringing Up Baby          1938          Howard Hawks   
97                    Unforgiven          1992        Clint Eastwood   
98  Guess Who's Coming to Dinner          1967        Stanley Kramer   
99           Yankee Doodle Dandy          1942        Michael Curtiz   

                      Production companies  Rank  
0                       RKO Radio Pictures     1  
1                    Warner Bros. Pictures     2  
2   Paramount Pictures, Alfran Productions     3  
3          Selznick International Pictures     4  
4                         Horizon Pictures     5  
..                                     ...   ...  
95                  C. V. Whitney Pictures    96  
96                      RKO Radio Pictures    97  
97                     The Malpaso Company    98  
98                       Columbia Pictures    99  
99                   Warner Bros. Pictures   100  

[100 rows x 5 columns]

Escrever um arquivo no formato HTML pode ser especialmente útil quando você deseja compartilhar os seus dados com pessoas que não têm acesso à biblioteca Pandas ou outras ferramentas de carregamento de dados.

Os dados podem ser consultados diretamente no navegador ou incorporados numa página web, facilitando muito a visualização.

### Criando o arquivo HTML
Vamos salvar o dataframe top_filmes em HTML. Para isso, numa nova célula, digitamos o nome do dataframe junto da função .to_html(). Entre os parênteses abrimos aspas simples e damos um nome para esse arquivo, como "top_filmes.html":

In [50]:
top_filmes.to_html('top_filmes.html')

### Visualizando os dados no navegador
Agora, vamos checar esse arquivo que foi salvo clicando em "Arquivos" (ícone da pasta) no menu lateral esquerdo e, na aba de Arquivos, clicamos nos três pontos verticais do item top_filmes.html e, em seguida, em "Fazer download".

Feito o download, vamos clicar no arquivo exibido na barra inferior do navegador. O arquivo é aberto automaticamente numa nova aba do navegador, exibindo a tabela que obtivemos no Colab com todos os dados em suas respectivas colunas, do 1 ao 100. Fantástico!

Conseguimos pegar aquela tabela e disponibilizá-la num formato possível de abrir no navegador e também incorporar numa página web. Você pode, inclusive, melhorar essa visualização se tiver alguma familiaridade com o front-end.

Além do formato HTML, podemos salvar esses dados em outros formatos. A pessoa que está criando esse sistema de recomendação provavelmente vai querer tratar esses dados e adicionar informações novas. Para isso, é interessante ter um arquivo no formato CSV ou um formato Excel para trabalhar mais facilmente.

### Salvando em formato CSV
Vamos salvar esse mesmo top_filmes no formato CSV. Para isso voltamos ao Colab e, numa nova célula, vamos digitar top_filmes e usar a função to_csv(). Entre os parênteses, passamos o nome do arquivo entre aspas simples, como 'top_filmes_1998.csv'.

Também precisamos passar o index=False quando salvamos um arquivo no formato CSV ou Excel, para evitar que uma nova coluna de index seja adicionada ao dataframe. Então:

In [51]:
top_filmes.to_csv('top_filmes_1998.csv', index=False)

Executamos essa célula e, novamente, voltamos ao menu de Arquivos. O arquivo top_filmes.1998.csv já foi salvo, então clicamos no menu de três pontos verticais e, depois, em "Copiar caminho" apenas para verificar se está tudo certo com o arquivo.

Fechamos o menu. Numa nova célula digitamos pd.read_csv() e, entre os parênteses, colamos o caminho copiado entre aspas:

In [52]:
pd.read_csv('/content/top_filmes_1998.csv')

Film  Release year              Director  \
0                   Citizen Kane          1941          Orson Welles   
1                     Casablanca          1942        Michael Curtiz   
2                  The Godfather          1972  Francis Ford Coppola   
3             Gone with the Wind          1939        Victor Fleming   
4             Lawrence of Arabia          1962            David Lean   
..                           ...           ...                   ...   
95                 The Searchers          1956             John Ford   
96              Bringing Up Baby          1938          Howard Hawks   
97                    Unforgiven          1992        Clint Eastwood   
98  Guess Who's Coming to Dinner          1967        Stanley Kramer   
99           Yankee Doodle Dandy          1942        Michael Curtiz   

                      Production companies  Rank  
0                       RKO Radio Pictures     1  
1                    Warner Bros. Pictures     2  
2   Paramount Pictures, Alfran Productions     3  
3          Selznick International Pictures     4  
4                         Horizon Pictures     5  
..                                     ...   ...  
95                  C. V. Whitney Pictures    96  
96                      RKO Radio Pictures    97  
97                     The Malpaso Company    98  
98                       Columbia Pictures    99  
99                   Warner Bros. Pictures   100  

[100 rows x 5 columns]

Ao executar essa célula, a saída recebida é o dataframe desejado. Então, temos um arquivo CSV contendo esses dados! A pessoa que está criando o sistema de recomendação pode utilizar esse arquivo e seguir com as futuras análises.

Mas, além de encontrar esses dados na Wikipedia, essa pessoa também encontrou um arquivo com informações mais detalhadas, contendo uma série de filmes com as notas que usuários atribuíram. Mas, esse arquivo está num formato diferente: o XML.

Agora temos um arquivo mais detalhado sobre os filmes, porém ele está no formato XML.

Para entender como esse formato é estruturado, vamos abrir o GitHub em que este arquivo está localizado. Ele é o arquivo imdb_top_1000.xml; ou seja, os dados desse arquivo foram obtidos do IMDB, uma base de dados que contém informações sobre filmes e séries, onde as pessoas atribuem uma nota às obras que assistem.

### O que é XML?
Esse nome é uma sigla da expressão em inglês Extensible Markup Language, ou "Linguagem de marcação estendida". Sua estrutura de tags é muito parecida com o HTML.

No nosso arquivo, temos uma tag logo no início chamada <data>. Essa é a tag raiz que indica o início do documento. Em seguida temos uma tag chamada <row>, "linha" em português. Para cada linha, temos várias tags que contêm as informações que estarão em cada uma das colunas.

Na primeira linha, por exemplo, temos as seguintes informações:

In [53]:
<data>
  <row>
    <index>0</index>
    <Poster_Link>https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX67_CR0,0,67,98_AL_.jpg</Poster_Link>
    <Series_Title>The Shawshank Redemption</Series_Title>
    <Released_Year>1994</Released_Year>
    <Certificate>A</Certificate>
    <Runtime>142 min</Runtime>
    <Genre>Drama</Genre>
    <IMDB_Rating>9.3</IMDB_Rating>
    <Overview>Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.</Overview>
    <Meta_score>80.0</Meta_score>
    <Director>Frank Darabont</Director>
    <Star1>Tim Robbins</Star1>
    <Star2>Morgan Freeman</Star2>
    <Star3>Bob Gunton</Star3>
    <Star4>William Sadler</Star4>
    <No_of_Votes>2343110</No_of_Votes>
    <Gross>28,341,469</Gross>
  </row>

SyntaxError: ignored

### Lendo um arquivo XML
Vamos ler esse arquivo no Google Colab. Para isso, fazemos seu upload clicando em "Arquivo > Fazer upload" no menu lateral esquerdo. Localizamos e selecionamos o arquivo imd_top_1000 e clicamos em "Abrir".

Com o arquivo carregado no menu de Arquivos, clicamos nos três pontos verticais e em "Copiar caminho". Fechamos o menu e voltamos para os códigos.

Para começar, importamos a biblioteca Pandas:

In [54]:
import pandas as pd

Em seguida, criamos uma variável chamada dados_imdb, que será igual a pd.red_xml(), uma nova função. Dentro dos parênteses, abrimos aspas simples e colamos o caminho para o arquivo:

In [55]:
dados_imdb = pd.read_xml('/content/imdb_top_1000.xml')

In [56]:
dados_imdb.head(3)

index                                        Poster_Link  \
0      0  https://m.media-amazon.com/images/M/MV5BMDFkYT...   
1      1  https://m.media-amazon.com/images/M/MV5BM2MyNj...   
2      2  https://m.media-amazon.com/images/M/MV5BMTMxNT...   

               Series_Title Released_Year Certificate  Runtime  \
0  The Shawshank Redemption          1994           A  142 min   
1             The Godfather          1972           A  175 min   
2           The Dark Knight          2008          UA  152 min   

                  Genre  IMDB_Rating  \
0                 Drama          9.3   
1          Crime, Drama          9.2   
2  Action, Crime, Drama          9.0   

                                            Overview  Meta_score  \
0  Two imprisoned men bond over a number of years...        80.0   
1  An organized crime dynasty's aging patriarch t...       100.0   
2  When the menace known as the Joker wreaks havo...        84.0   

               Director           Star1           Star2          Star3  \
0        Frank Darabont     Tim Robbins  Morgan Freeman     Bob Gunton   
1  Francis Ford Coppola   Marlon Brando       Al Pacino     James Caan   
2     Christopher Nolan  Christian Bale    Heath Ledger  Aaron Eckhart   

            Star4  No_of_Votes        Gross  
0  William Sadler      2343110   28,341,469  
1    Diane Keaton      1620367  134,966,411  
2   Michael Caine      2303232  534,858,444

Temos as seguintes informações no dataframe: um link para o pôster de cada um dos filmes, os títulos, ano de publicação, certificado, duração do filme, gênero, nota no IMDB, sinopse, meta score, diretor, atores principais, número de votos e orçamento.

### Escrevendo um arquivo XML
Fizemos a leitura de um arquivo XML e entendemos sua estrutura! Agora, podemos escrever no formato XML.

Para isso, numa nova célula, vamos escrever o nome da nossa variável dados_imdb e usar a função to_xml(''). Dentro dos parênteses e aspas, damos o nome do arquivo, como "filmes_imdb.xml":

In [57]:
dados_imdb.to_xml('filmes_imdb.xml')

Ao executar essa célula, salvamos um arquivo no formato XML. Verificamos um novo arquivo chamado filmes_imdb.xml no menu de Arquivos!

Essa função to_xml(), para salvar no formato XML, é muito útil quando trabalhamos com bancos de dados ou outros sistemas que se integrem facilmente a esse formato.

# Aula 05

Nesta aula, vamos utilizar duas bibliotecas: pandas e SQLAlchemy. É importante ter certeza de que a versão do SQLAlchemy que você está utilizando seja compatível com a biblioteca pandas, para que os códigos da aula possam ser executados corretamente.

Então, antes de tudo, importe as duas bibliotecas com o seguinte código:

In [58]:
import pandas as pd
import sqlalchemy


Para checar a versão da biblioteca SQLAlchemy, use o seguinte código:

In [59]:
sqlalchemy.__version__


'1.4.49'

Se a versão da SQLAlchemy for 2.0.16 ou uma versão mais atual, você deve atualizá-la para uma versão inferior a 2.0 com o seguinte código:

In [60]:
pip install --upgrade 'sqlalchemy<2.0'

Após a instalação bem-sucedida, é importante reiniciar o ambiente de execução do Google Colab para garantir que as alterações sejam aplicadas.

Para fazer isso, clique no menu superior em "Ambiente de execução" e selecione a opção "Reiniciar ambiente de execução". Depois de reiniciar, você pode executar as células novamente e prosseguir com os próximos códigos.

Utilizamos dados em HTML e XML, agora temos um novo conjunto de dados para serem lidos.

O time de dados de uma Instituição Financeira possui um arquivo CSV que contém os dados de todos os clientes cadastrados. Porém, o que eles querem é pegar esse arquivo, colocar em um banco de dados local e a partir dele realizar consultas SQL. Assim será possível analisar dados, obter insights e tomar decisões estratégicas.

Quando falamos sobre banco de dados nos referimos a um sistema de gerenciamento no qual conseguimos armazenar, gerenciar e atualizar dados.

A linguagem trabalhada em banco de dados é a SQL, uma sigla que vem do inglês "Strictured Quert Language" e significa Linguagem de Consulta Estruturada.

Será que conseguimos trabalhar com a criação de um banco de dados local no Google Colab com essas consultas SQL? É possível essa integração?

Sim, é possível. Porém, para isso precisamos importar outra biblioteca, a SQLAlchemy, que permite a criação do banco. É isso que faremos agora.

### Criando um banco de dados local
No Google Colab, criamos uma nova linha de código. Nela, escrevemos import sqlalchemy e executamos a célula.

Agora, precisamos fazer algumas importações. Na linha de baixo, escrevemos from sqlalchemy import. A primeira importação será create_engine, que serve para criar o motor, ou seja, a conexão com o banco de dados que o fará funcionar.

Na mesma linha, inserimos uma vírgula e a importação MetaData. Essa é uma classe que representa os meta dados do banco de dados, isso inclui informações sobre as tabelas, colunas e outros objetos.

Também importamos a classe Table que representa uma tabela em um banco de dados e é usada para manipular dados em uma tabela específica.

Por fim, importamos a função inspect, que permite inspecionar a estrutura do banco de dados. Em seguida, executamos a célula.

Agora, vamos criar o banco de dados. Para isso, criamos uma variável chamada engine. Dela, chamamos o create_engine(). Dentro das chaves abrimos aspas simples e escrevemos o banco de dados que será utilizado, 'sqlite:///:memory:'.

Nesse caso, usaremos o SQLite, um banco de dados que vem naturalmente instalado no Google Colab. Nesse trecho de código o memory indica que estamos usando um banco de dados local.

In [61]:
import sqlalchemy
from sqlalchemy import create_engine, MetaData, Table, inspect
engine = create_engine('sqlite:///:memory:')


Agora, nosso desafio é escrever no banco de dados local. Para isso, no GitHub, clicamos no arquivo clientes_banco.csv. Depois, no centro da tela, clicamos em "View raw" para acessarmos os dados brutos.

Feito isso, abre uma nova página. Copiamos o link e voltamos para o Google Colab.

### Escrevendo em um banco de dados
Em uma nova linha, criamos a variável url. Inserimos o símbolo de igual, seguido de duas aspas simples. Dentro dela, colamos o link. Em seguida, executamos.

In [62]:
#Código omitido

url = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/clientes_banco.csv'

Para fazer a leitura do arquivo, fazemos um import pandas as pde executamos a célula.

Agora, vamos criar uma variável chamada dados. Ela será igual a pd.read_csv(url).

In [64]:
import pandas as pd
dados = pd.read_csv(url)
dados.head()

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0     5008804     32   Ensino superior  União-estável                2   
1     5008805     32   Ensino superior  União-estável                2   
2     5008806     58      Ensino médio         Casado                2   
3     5008808     52      Ensino médio       Solteiro                1   
4     5008809     52      Ensino médio       Solteiro                1   

    Categoria_de_renda   Ocupacao  Anos_empregado  Rendimento_anual  \
0            Empregado      Outro              12          427500.0   
1            Empregado      Outro              12          427500.0   
2            Empregado  Segurança               3          112500.0   
3  Associado comercial     Vendas               8          270000.0   
4  Associado comercial     Vendas               8          270000.0   

   Tem_carro                   Moradia  
0          1       Apartamento alugado  
1          1       Apartamento alugado  
2          1  Casa/apartamento próprio  
3          0  Casa/apartamento próprio  
4          0  Casa/apartamento próprio

São várias informações dos clientes da instituição financeira.

Para colocá-las no nosso banco de dados utilizaremos a função dados.to_sql(), que deixará o dataframe no formato do banco. Dentro do parênteses, colocamos duas aspas simples e definimos o nome da tabela que será criada. Nesse caso será 'clientes'.

Na mesma linha inserimos uma vírgula e escrevemos a variável engine, que é o motor do banco. Por fim, escrevemos o parâmetro index=False.

In [65]:
dados.to_sql('clientes', engine, index=False)

438463

Pronto, passamos os arquivos para o to_sql().

Mas, como sabemos se a tabela foi realmente criada no banco de dados?

Lembra que anteriormente importamos uma função chamada Função Inspect? Vamos utilizá-la novamente para inspecionar o banco de dados.

Criamos uma variável chamada inspector. Inserimos o símbolo de igual seguido da função inspect(). Dentro dela, vamos passar o engine e executar a célula.

Dessa forma, conseguimos verificar o que temos no banco de dados e inspecionar algumas informações.

In [66]:
#Código omitido

inspector = inspect(engine)

Agora, podemos printar o nome das tabelas que temos dentro do banco de dados. Para fazer isso, escrveemos print(). Em seguida, passamos o inspector.get_table_names(), essa função devolve os nomes das tabelas que estão dentro do banco de dados.

In [67]:
print(inspector.get_table_names())

['clientes']


Criamos uma tabela chamada Clientes que possui as informações das pessoas cadastradas na instituição financeira.

Agora, descobriremos como acessar essas informações por meio de consultas SQL.

Para isso, criamos uma variável chamada query. Inserimos o símbolo de igual e duas aspas simples.

Dentro das aspas escrevemos exatamente o que queremos consultar em SQL. Nesse caso, o que o time de dados quer é separar as pessoas que estão com a categoria de renda preenchidas como "Empregado", ou seja, só as pessoas que estão trabalhando no momento.

Quando trabalhamos com SQL utilizamos cláusulas, ou seja, palavras que possuem funções específicas para a consulta.

Lembrando que em SQL as cláusulas são escritas em caixa alta.

Sendo assim, após as aspas, escrevemos SELECT seguido de *. Esse asterisco indica que queremos selecionar todas as colunas da tabela.

Agora, precisamos especificar qual tabela é essa. Então, após * inserimos a cláusula FROM clientes.

Na mesma linha, escrevemos a cláusula WHERE, que filtra as informações, seguido do nome da coluna que queremos consultar Categoria_de_renda. Logo após escrevemos ="Empregado" e executamos.

Estamos pedindo para selecionar todas as colunas da tabela clientes na qual a categoria de renda seja igual a "Empregado".

In [72]:
query = 'SELECT * FROM clientes WHERE Categoria_de_renda="Empregado"'

Para ler uma consulta em SQL criaremos a variável empregados = pd.read_sql(). Dentro do parêntese, passamos a consulta e o motor do bando de dados, query, engine. Em seguida, a executamos.

Agora, na linha de seguinte, escrevemos empregados e executamos a célula. Feito isso, temos o seguinte retorno:

In [74]:
empregados = pd.read_sql(query,engine)
empregados

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0          5008804     32   Ensino superior  União-estável                2   
1          5008805     32   Ensino superior  União-estável                2   
2          5008806     58      Ensino médio         Casado                2   
3          5008815     46   Ensino superior         Casado                2   
4          5112956     46   Ensino superior         Casado                2   
...            ...    ...               ...            ...              ...   
226054     6837905     43      Ensino médio         Casado                3   
226055     6837906     43      Ensino médio         Casado                3   
226056     6839936     34      Ensino médio         Casado                3   
226057     6840222     43      Ensino médio       Solteiro                1   
226058     6842885     51      Ensino médio         Casado                2   

       Categoria_de_renda          Ocupacao  Anos_empregado  Rendimento_anual  \
0               Empregado             Outro              12          427500.0   
1               Empregado             Outro              12          427500.0   
2               Empregado         Segurança               3          112500.0   
3               Empregado     Contabilidade               2          270000.0   
4               Empregado     Contabilidade               2          270000.0   
...                   ...               ...             ...               ...   
226054          Empregado             Outro               7          355050.0   
226055          Empregado             Outro               7          355050.0   
226056          Empregado  Construção Civil               5          135000.0   
226057          Empregado  Construção Civil               8          103500.0   
226058          Empregado            Vendas               3          121500.0   

        Tem_carro                   Moradia  
0               1       Apartamento alugado  
1               1       Apartamento alugado  
2               1  Casa/apartamento próprio  
3               1  Casa/apartamento próprio  
4               1  Casa/apartamento próprio  
...           ...                       ...  
226054          1  Casa/apartamento próprio  
226055          1  Casa/apartamento próprio  
226056          1  Casa/apartamento próprio  
226057          0  Casa/apartamento próprio  
226058          0  Casa/apartamento próprio  

[226059 rows x 11 columns]

### Conseguimos fazer nossa primeira consulta SQL!

Para salvá-la como uma nova tabela escrevemos empregados.to_sql(). Dentro do parêntese inserimos aspas simples e dentro dela escrevemos empregados. Adicionamos uma vírgula e passamos o parâmetro con=engine seguido de index=False e executamos.

In [75]:
empregados.to_sql('empregados', con=engine, index=False)

226059

Utilizamos o read_sql para lermos uma consulta, mas e se quisermos ler uma tabela inteira como a que acabamos de salvar?

Para isso, utilizamos a função pd.read_sql_table(). Dentro do parêntese inserimos aspas simples, seguido do nome da tabela que queremos executar 'empregados' e engine. Executamos em sequência.

In [76]:
pd.read_sql_table('empregados', engine)

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0          5008804     32   Ensino superior  União-estável                2   
1          5008805     32   Ensino superior  União-estável                2   
2          5008806     58      Ensino médio         Casado                2   
3          5008815     46   Ensino superior         Casado                2   
4          5112956     46   Ensino superior         Casado                2   
...            ...    ...               ...            ...              ...   
226054     6837905     43      Ensino médio         Casado                3   
226055     6837906     43      Ensino médio         Casado                3   
226056     6839936     34      Ensino médio         Casado                3   
226057     6840222     43      Ensino médio       Solteiro                1   
226058     6842885     51      Ensino médio         Casado                2   

       Categoria_de_renda          Ocupacao  Anos_empregado  Rendimento_anual  \
0               Empregado             Outro              12          427500.0   
1               Empregado             Outro              12          427500.0   
2               Empregado         Segurança               3          112500.0   
3               Empregado     Contabilidade               2          270000.0   
4               Empregado     Contabilidade               2          270000.0   
...                   ...               ...             ...               ...   
226054          Empregado             Outro               7          355050.0   
226055          Empregado             Outro               7          355050.0   
226056          Empregado  Construção Civil               5          135000.0   
226057          Empregado  Construção Civil               8          103500.0   
226058          Empregado            Vendas               3          121500.0   

        Tem_carro                   Moradia  
0               1       Apartamento alugado  
1               1       Apartamento alugado  
2               1  Casa/apartamento próprio  
3               1  Casa/apartamento próprio  
4               1  Casa/apartamento próprio  
...           ...                       ...  
226054          1  Casa/apartamento próprio  
226055          1  Casa/apartamento próprio  
226056          1  Casa/apartamento próprio  
226057          0  Casa/apartamento próprio  
226058          0  Casa/apartamento próprio  

[226059 rows x 11 columns]

Lembre-se sempre dessa diferença, o read_sql permite ler uma consulta e o read_sql_table uma tabela completa.

Além disso, também podemos inserir outros parâmetros, como especificar quais colunas queremos que sejam lidas.

Para testarmos, copiamos a mesma linha de código que escrevemos anteriormente e colamos em uma nova linha.

Depois de engine, adicionamos o parâmetro colums=[]. Dentro de colchetes adicionamos aspas simples e dentro delas adicionamos as colunas que queremos visualizar, sendo: 'ID_cliente', 'Grau_escolaridade', 'Rendimento_anual'.

In [77]:
pd.read_sql_table('empregados', engine, columns=['ID_Cliente', 'Grau_escolaridade', 'Rendimento_anual'])

ID_Cliente Grau_escolaridade  Rendimento_anual
0          5008804   Ensino superior          427500.0
1          5008805   Ensino superior          427500.0
2          5008806      Ensino médio          112500.0
3          5008815   Ensino superior          270000.0
4          5112956   Ensino superior          270000.0
...            ...               ...               ...
226054     6837905      Ensino médio          355050.0
226055     6837906      Ensino médio          355050.0
226056     6839936      Ensino médio          135000.0
226057     6840222      Ensino médio          103500.0
226058     6842885      Ensino médio          121500.0

[226059 rows x 3 columns]

A partir disso o time de dados já pode fazer algumas análises.

Mas, e se algum cliente não estiver mais cadastrado na instituição financeira ou tiver seu rendimento anual atualizado?

Existem inúmeras situações no dia a dia que podem precisar da atualização das informações do banco de dados.

Para colocar isso em prática, vamos visualizar novamente os dados da tabela Clientes. Criamos uma variável query, inserimos o símbolo de igual e aspas duplas. Dentro delas escrevemos SELECT * FROM clientes e executamos a célula.

In [78]:
query = 'SELECT * FROM clientes'

Em uma nova linha, escrevemos pd.read_sql(). Dentro do parêntese passamos nossa consulta query e o motor do banco engine. Executamos a célula.

In [79]:
pd.read_sql(query, engine)

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0          5008804     32   Ensino superior  União-estável                2   
1          5008805     32   Ensino superior  União-estável                2   
2          5008806     58      Ensino médio         Casado                2   
3          5008808     52      Ensino médio       Solteiro                1   
4          5008809     52      Ensino médio       Solteiro                1   
...            ...    ...               ...            ...              ...   
438458     6840104     62      Ensino médio     Divorciado                1   
438459     6840222     43      Ensino médio       Solteiro                1   
438460     6841878     22   Ensino superior       Solteiro                1   
438461     6842765     59      Ensino médio         Casado                2   
438462     6842885     51      Ensino médio         Casado                2   

         Categoria_de_renda          Ocupacao  Anos_empregado  \
0                 Empregado             Outro              12   
1                 Empregado             Outro              12   
2                 Empregado         Segurança               3   
3       Associado comercial            Vendas               8   
4       Associado comercial            Vendas               8   
...                     ...               ...             ...   
438458          Pensionista             Outro               0   
438459            Empregado  Construção Civil               8   
438460  Associado comercial            Vendas               1   
438461          Pensionista             Outro               0   
438462            Empregado            Vendas               3   

        Rendimento_anual  Tem_carro                   Moradia  
0               427500.0          1       Apartamento alugado  
1               427500.0          1       Apartamento alugado  
2               112500.0          1  Casa/apartamento próprio  
3               270000.0          0  Casa/apartamento próprio  
4               270000.0          0  Casa/apartamento próprio  
...                  ...        ...                       ...  
438458          135000.0          0  Casa/apartamento próprio  
438459          103500.0          0  Casa/apartamento próprio  
438460           54000.0          0          Mora com os pais  
438461           72000.0          0  Casa/apartamento próprio  
438462          121500.0          0  Casa/apartamento próprio  

[438463 rows x 11 columns]

### Atualizando um banco de dados
Suponhamos que a pessoa de ID 5008804 cancelou sua conta na instituição financeira. Isso significa que ela não faz mais parte do quadro de clientes.

Para tirá-la da tabela precisamos realizar uma consulta. Então, escrevemos query = ''. Dentro das aspas, inserimos a instrução DELETEseguido da cláusula FROM clientes. Agora, especificamos qual cliente será deletado, então, escrevemos WHERE seguido do nome da coluna ID_Cliente e o número do ID 5008804.

Apertamos "Enter" para a linha de baixo. Agora, fazemos um contexto with. Isso garante que a conexão com o banco de dados seja fechada corretamente após a execução da consulta. Depois, usamos o método engine.connect(), seguido de as conn.

Na linha de baixo, chamamos o conn.execute(query). Em seguida, executamos.

Com isso estamos usando um método chamado connect para estabelecer uma conexão com o banco de dados. Estamos pedindo para executar a query com o método execute que quando chamado, executa a instrução SQL diretamente no banco de dados, usando a conexão estabelecida.

In [80]:
query = 'DELETE FROM clientes WHERE ID_Cliente=5008804'
with engine.connect() as conn:
    conn.execute(query)

Agora, vamos conferir se realmente não temos mais o cliente no banco de dados. Ao invés de fazer uma consulta, leremos a tabela clientes inteira.

Para isso, escrevemos pd.read_sql_table(). Dentro do parêntese escrevemos 'clientes', engine e executamos.

In [82]:
pd.read_sql_table('clientes', engine)

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0          5008805     32   Ensino superior  União-estável                2   
1          5008806     58      Ensino médio         Casado                2   
2          5008808     52      Ensino médio       Solteiro                1   
3          5008809     52      Ensino médio       Solteiro                1   
4          5008810     52      Ensino médio       Solteiro                1   
...            ...    ...               ...            ...              ...   
438457     6840104     62      Ensino médio     Divorciado                1   
438458     6840222     43      Ensino médio       Solteiro                1   
438459     6841878     22   Ensino superior       Solteiro                1   
438460     6842765     59      Ensino médio         Casado                2   
438461     6842885     51      Ensino médio         Casado                2   

         Categoria_de_renda          Ocupacao  Anos_empregado  \
0                 Empregado             Outro              12   
1                 Empregado         Segurança               3   
2       Associado comercial            Vendas               8   
3       Associado comercial            Vendas               8   
4       Associado comercial            Vendas               8   
...                     ...               ...             ...   
438457          Pensionista             Outro               0   
438458            Empregado  Construção Civil               8   
438459  Associado comercial            Vendas               1   
438460          Pensionista             Outro               0   
438461            Empregado            Vendas               3   

        Rendimento_anual  Tem_carro                   Moradia  
0               427500.0          1       Apartamento alugado  
1               112500.0          1  Casa/apartamento próprio  
2               270000.0          0  Casa/apartamento próprio  
3               270000.0          0  Casa/apartamento próprio  
4               270000.0          0  Casa/apartamento próprio  
...                  ...        ...                       ...  
438457          135000.0          0  Casa/apartamento próprio  
438458          103500.0          0  Casa/apartamento próprio  
438459           54000.0          0          Mora com os pais  
438460           72000.0          0  Casa/apartamento próprio  
438461          121500.0          0  Casa/apartamento próprio  

[438462 rows x 11 columns]

Analisando a tabela, percebemos que antes ela começava pelo cliente de ID 5008804. Depois de aplicar o DELET ela começa pelo cliente de ID 5008805. Isso significa que deu certo.

***Mas, e se só quisermos atualizar um dado ao invés de apagá-lo?***

O cliente 5008808 está com o grau de escolaridade como Ensino médio. Porém, ele fez faculdade e deseja mudar para Ensino superior.

Para isso, em uma nova linha escrevemos a consulta query =''. Dentro das aspas usamos a clausula UPDATE seguido do nome da tabela clientes e a clausula SET.

Após, definimos qual coluna será alterada, então Grau_escolaridade. Inserimos o símbolo de igual, seguido da informação que queremos atualizar entre aspas duplas, nesse caso "Ensino superior".

Definimos onde isso será alterado WHERE ID_Cliente. Inserimos o símbolo de igual e o ID do cliente 5008808.

Agora, copiamos o mesmo código do contexto with que usamos anteriormente e colamos abaixo dessa nova consulta. Em seguida, executamos a célula. Dessa forma:

In [83]:
query = 'UPDATE clientes SET Grau_escolaridade="Ensino superior" WHERE ID_Cliente=5008808'
with engine.connect() as conn:
    conn.execute(query)

Para visualizar se deu certo, leremos a tabela de clientes completa. Escrevemos pd.read_sql_table() e dentro do parêntese passamos 'clientes', engine.

In [84]:
pd.read_sql_table('clientes', engine)

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0          5008805     32   Ensino superior  União-estável                2   
1          5008806     58      Ensino médio         Casado                2   
2          5008808     52   Ensino superior       Solteiro                1   
3          5008809     52      Ensino médio       Solteiro                1   
4          5008810     52      Ensino médio       Solteiro                1   
...            ...    ...               ...            ...              ...   
438457     6840104     62      Ensino médio     Divorciado                1   
438458     6840222     43      Ensino médio       Solteiro                1   
438459     6841878     22   Ensino superior       Solteiro                1   
438460     6842765     59      Ensino médio         Casado                2   
438461     6842885     51      Ensino médio         Casado                2   

         Categoria_de_renda          Ocupacao  Anos_empregado  \
0                 Empregado             Outro              12   
1                 Empregado         Segurança               3   
2       Associado comercial            Vendas               8   
3       Associado comercial            Vendas               8   
4       Associado comercial            Vendas               8   
...                     ...               ...             ...   
438457          Pensionista             Outro               0   
438458            Empregado  Construção Civil               8   
438459  Associado comercial            Vendas               1   
438460          Pensionista             Outro               0   
438461            Empregado            Vendas               3   

        Rendimento_anual  Tem_carro                   Moradia  
0               427500.0          1       Apartamento alugado  
1               112500.0          1  Casa/apartamento próprio  
2               270000.0          0  Casa/apartamento próprio  
3               270000.0          0  Casa/apartamento próprio  
4               270000.0          0  Casa/apartamento próprio  
...                  ...        ...                       ...  
438457          135000.0          0  Casa/apartamento próprio  
438458          103500.0          0  Casa/apartamento próprio  
438459           54000.0          0          Mora com os pais  
438460           72000.0          0  Casa/apartamento próprio  
438461          121500.0          0  Casa/apartamento próprio  

[438462 rows x 11 columns]

Analisando a tabela, conseguimos identificar que o cliente 5008808 agora consta com o grau de escolaridade como Ensino superior. Deu tudo certo!

# Para Saber Mais

## Aula 01

Giovanna é uma cientista de dados que trabalha em uma empresa de comércio eletrônico. Ela é responsável por analisar os dados de vendas para identificar padrões e tendências que possam ajudar a empresa a tomar decisões informadas.

Recentemente, ela recebeu uma nova tarefa: analisar um arquivo CSV contendo informações sobre as vendas da empresa em um determinado período. Para isso, Giovanna tentou fazer a leitura do um arquivo CSV no Google Colab, utilizando a biblioteca Pandas com o seguinte comando.

Porém, surgiu o erro abaixo:

In [ ]:
import pandas as pd
df = pd.read_csv('/content/dados_mercado.csv')

Em português a mensagem quer dizer UnicodeDecodeError: o codec 'utf-8' não pode decodificar o byte 0xe7 na posição 18: byte de continuação inválido.

O erro de encoding ocorre quando a biblioteca Pandas não consegue interpretar corretamente os caracteres de um arquivo CSV. Isso pode acontecer quando ele contém caracteres especiais que não são reconhecidos pela biblioteca Pandas ou quando foi salvo em um formato de codificação diferente do esperado.

Para resolver esse erro, é necessário identificar a codificação correta do arquivo CSV e especificá-la ao carregar o arquivo com a biblioteca Pandas. Essa codificação padrão é o UTF-8, mas em alguns casos, o arquivo pode ter sido salvo com uma codificação diferente, como ISO-8859-1.

O UTF-8 é uma codificação de caracteres universal usada para representar caracteres de diferentes idiomas de forma compatível com a internet e com sistemas de computador em geral. A sigla UTF significa Unicode Transformation Format (Formato de Transformação Unicode) e o número 8 indica que essa codificação associa uma sequência de 1 a 4 bytes (8 a 32 bits) com cada caractere.

A codificação UTF-8 é amplamente utilizada na internet e em sistemas de computador em todo o mundo, pois permite a representação de caracteres de diferentes idiomas em um único conjunto de caracteres. Além disso, essa codificação é capaz de preservar a compatibilidade com outras mais antigas, como ASCII, o que a torna uma escolha popular para a criação e compartilhamento de arquivos de texto.

Pode ser que você esteja pensando neste momento: como será que a Giovanna conseguiu descobrir qual é a codificação do arquivo que ela está tentando ler?

Existem algumas formas para descobrir isso, no entanto, teremos a oportunidade de experimentar uma maneira prática de fazer isso no próprio Google Colab. Vamos lá?

Nós podemos usar uma biblioteca chamada chardet para detectar o encoding de um arquivo CSV. Para utilizar essa biblioteca no Google Colab, basta realizar sua importação:


In [ ]:
import chardet
with open('/content/dados_mercado.csv', 'rb') as file:
    print(chardet.detect(file.read()))

Note que a primeira linha deste código abre o arquivo CSV em modo de leitura binária rb e atribui o objeto de arquivo retornado a uma variável chamada file.

Na segunda linha do código, o conteúdo do arquivo CSV é lido usando o método read() e o resultado é passado para a função chardet.detect(), que retorna um dicionário contendo informações sobre a codificação mais provável do arquivo. O resultado é impresso com a função print() que mostra a codificação e a confiança associada a essa codificação.

Ao executar o código Giovanna obteve o seguinte resultado:

In [ ]:
{'encoding': 'ISO-8859-1', 'confidence': 0.73, 'language': ''}

Agora ela sabe que o arquivo CSV provavelmente possui a codificação ISO-8859-1 com uma confiança de 0.73. Para especificar a codificação correta ao carregar o arquivo CSV com a biblioteca Pandas, é possível usar um parâmetro chamado encoding:

In [ ]:
df = pd.read_csv('/content/dados_mercado.csv', encoding='ISO-8859-1')

Desta forma, a biblioteca Pandas irá carregar o arquivo CSV usando a codificação ISO-8859-1, o que vai resolver o erro de encoding. Então, se algum dia você tentar ler um arquivo e surgir esse mesmo erro, lembre-se dessa dica!

A biblioteca Pandas é uma das ferramentas mais poderosas disponíveis para a análise de dados em Python. Ela oferece uma ampla variedade de funcionalidades que tornam o processo de manipulação e análise de dados muito mais fácil e eficiente.

Para aproveitar ao máximo todas as funcionalidades da biblioteca, é essencial explorar a sua documentação, que é extensa e bem organizada, e pode ser facilmente acessada no modo on-line. Confira as indicações:

Função read_csv
Função to_csv
Explorar a documentação da biblioteca é importante por diversas razões. Ela pode ajudar a entender como as funções e métodos da biblioteca funcionam e como elas podem ser usadas para analisar e manipular os dados.

Além disso, a documentação fornece detalhes sobre os parâmetros de cada função e exemplos de como eles podem ser usados na prática. Então, busque aprofundar os seus estudos nesses parâmetros das funções read_csv e to_csv e aprenda mais sobre cada um deles.

## Aula 02

O Microsoft Excel é uma das ferramentas de planilha mais utilizadas no mundo, sendo amplamente utilizado para armazenar e analisar dados em formato de tabela. No vídeo anterior, demonstramos como a função read_excel pode ser utilizada para ler um arquivo Excel no formato xlsx. No entanto, essa função é capaz de ler arquivos em outros formatos, como: xls, xlsm, xlsb, odf, ods e odt.

Vamos entender um pouco mais sobre esses diferentes tipos de arquivos?

### xls
O xls é um formato de arquivo do Excel mais antigo e usado até a versão de 2003.

### xlsx
Já o xlsx é o formato de arquivo padrão do Excel a partir da versão 2007. Esse formato é baseado em XML (Extensible Markup Language - Linguagem de marcação extensível) e é amplamente suportado por outras ferramentas de planilha eletrônica, incluindo o Google Planilhas.

Atenção: Se surgiram algumas dúvidas com o termo XML, não se preocupe! Mais adiante teremos uma aula sobre esse tema. Nela você entenderá o que é esse formato, na medida em que lê e escreve em XML.

### xlsm
Há também o xlsm, uma extensão de arquivo usada pelo Excel para armazenar planilhas que contêm as macros. Estas são sequências de comandos ou instruções que podem ser executadas automaticamente para realizar tarefas específicas na planilha.

Então, o formato xlsm permite que as macros sejam salvas juntamente com a planilha, para que possam ser executadas sempre que a planilha for aberta.

### xlsb
Por fim, temos o formato xlsb, uma extensão de arquivo usada pelo Excel para armazenar planilhas em formato binário. A codificação binária permite que as planilhas sejam abertas e salvas com mais rapidez do que aquelas no formato xlsx.

Já os formatos odf, ods e odt são arquivos abertos, livres e universais que podem ser usados por qualquer software, ou seja, foram criados para serem independentes de plataformas, isso significa que podem ser usados em sistemas operacionais diferentes, como Windows, Linux e Mac OS.

Além disso, são independentes de aplicativos e podem ser usados em vários programas diferentes, incluindo o OpenOffice, o LibreOffice, o Google Docs e o Microsoft Office. Esse padrão de arquivos foi criado e é mantido pela OASIS (Organization for the Advancement of Structured Information Standards), uma organização internacional criada para desenvolver e promover padrões digitais para uso na Internet.

O Google Planilhas é uma ferramenta de planilha eletrônica baseada em nuvem que permite criar, editar e colaborar em planilhas de forma fácil e conveniente. É um dos aplicativos do Google Workspace que oferece uma alternativa ao Microsoft Excel.

Com o Google Planilhas é possível criar e formatar planilhas, adicionar fórmulas e funções, criar gráficos e tabelas dinâmicas, além de trabalhar com dados em tempo real com outras pessoas. Ele também suporta a importação e exportação de vários formatos de arquivos, como CSV e XLSX.

Uma das principais vantagens do Google Planilhas é a colaboração em tempo real. Várias pessoas podem trabalhar simultaneamente na mesma planilha, visualizando as alterações simultaneamente. Isso torna mais fácil trabalhar em projetos em equipe, aumentando a eficiência e a produtividade.

## Aula 03

Normalização de dados é um processo importante em ciência de dados que tem como objetivo organizar e padronizar dados para facilitar a análise e comparação entre eles. Quando se trata de dados no formato JSON (JavaScript Object Notation - Notação de Objetos JavaScript), é comum que eles estejam aninhados, o que pode dificultar sua análise e manipulação.

A biblioteca Pandas possui uma função chamada json_normalize() que permite a transformação dos dados em um formato tabular, facilitando a visualização e análise das informações. A seguir vamos aprender como usar essa função para normalizar diferentes tipos de JSON em DataFrames.

Normalizando um JSON simples
Abaixo temos uma variável chamada dados e dentro dela há um objeto JSON com três chaves e seus respectivos valores:

In [ ]:
dados = {'Pesquisa': 'Principais Indicadores de Doenca Cardiaca', 'Ano': 2020, 'Numero_Pacientes':3}


Para normalizar essa variável, podemos passa-lá dentro da função json_normalize e analisar o DataFrame obtido:

In [ ]:
df = pd.json_normalize(dados)
df


O resultado parece ótimo! Temos 3 colunas que são as nossas chaves e uma linha contendo os valores para cada chave.

### Normalizando um JSON com vários níveis
Existem situações em que o arquivo JSON pode conter mais de um objeto, como é o caso do exemplo abaixo, no qual temos uma lista, armazenada na variável json_lista, contendo dois objetos JSON:

In [ ]:
json_lista = [
    { 'ID': '01', 'Faixa_etaria': '55-59', 'Sexo_biologico': 'feminino'},
    { 'ID': '02', 'Faixa_etaria': '80 ou +', 'Sexo_biologico': 'feminino'}
]


Para normalizar essa lista podemos aplicar a função json_normalize:

In [ ]:
pd.json_normalize(json_lista)


A função json_normalize() é capaz de converter cada registro da lista em uma linha de forma tabular.

### Normalizando um JSON com uma lista aninhada
Bom, notamos que a função json_normalize() funciona muito bem nas situações anteriores, mas e em outras situações?

### Dados como um dicionário
Vamos começar analisando a normalização quando os dados são um dicionário. Temos um dicionário armazenado na variável json_obj. Note que na chave “Saude” temos outro dicionário:

In [ ]:
json_obj = {
    'ID': '01',
    'Faixa_etaria': '55-59',
    'Sexo_biologico': 'Feminino',
    'Saude': {'Dificuldade_caminhar': 'Nao',
              'Atividade_fisica': 'Sim',
              'IMC': 16.6,
              'Doenca_cardiaca': 'Nao',
          }
      }


In [ ]:
pd.json_normalize(json_obj)


O DataFrame gerado possui uma coluna para cada informação contida no dicionário que estava em “Saude”. As colunas criadas possuem o prefixo “Saude.”, pois as informações vieram dessa mesma chave.

### Dados como uma lista de dicionários
Agora nós temos uma lista de dicionários armazenada na variável json_list:

In [ ]:
json_list = [
    {
    'ID': '01',
    'Faixa_etaria': '55-59',
    'Sexo_biologico': 'Feminino',
    'Saude': {'Dificuldade_caminhar': 'Nao',
              'Atividade_fisica': 'Sim',
              'IMC': 16.6,
              'Doenca_cardiaca': 'Nao',
          }
      },
      {
          'ID': '02',
          'Faixa_etaria': '80 ou +',
          'Sexo_biologico': 'Feminino',
          'Saude': {'Dificuldade_caminhar': 'Nao',
                    'Atividade_fisica': 'Sim',
                    'IMC': 20.34,
                    'Doenca_cardiaca': 'Sim'}
       }
       ]


In [ ]:
pd.json_normalize(json_list)


Podemos analisar que todos os valores aninhados em cada registro da lista foram convertidos em colunas separadas. E os dados que nós normalizamos no vídeo anterior? Lembra que a normalização deles foi feita de um jeito diferente?

Recapitulando, vamos copiar os dados do arquivo pacientes_2.json e armazená-los numa variável chamada dados_dict.

In [ ]:
dados_dict = {
  "Pesquisa": "Principais Indicadores de Doenca Cardiaca",
  "Ano": 2020,
  "Pacientes": [
    {
      "ID": "01",
      "Faixa_etaria": "55-59",
      "Sexo_biologico": "Feminino",
      "Raça": "Branca",
      "IMC": 16.6,
      "Fumante": "Sim",
      "Consumo_alcool": "Nao",
      "Saude_fisica": 3,
      "Saude_mental": 30,
      "Dificuldade_caminhar": "Nao",
      "Atividade_fisica": "Sim",
      "Saude_geral": "Muito boa",
      "Horas_sono": 5,
      "Problemas_saude": [
        "Diabetes",
        "Asma",
        "Cancer_pele"
      ]
    },
    {
      "ID": "02",
      "Faixa_etaria": "80 ou +",
      "Sexo_biologico": "Feminino",
      "Raça": "Branca",
      "IMC": 20.34,
      "Fumante": "Nao",
      "Consumo_alcool": "Nao",
      "Saude_fisica": 0,
      "Saude_mental": 0,
      "Dificuldade_caminhar": "Nao",
      "Atividade_fisica": "Sim",
      "Saude_geral": "Muito boa",
      "Horas_sono": 7,
      "Problemas_saude": [
        "AVC"
      ]
    },
    {
      "ID": "03",
      "Faixa_etaria": "65-69",
      "Sexo_biologico": "Masculino",
      "Raça": "Branca",
      "IMC": 26.58,
      "Fumante": "Sim",
      "Consumo_alcool": "Nao",
      "Saude_fisica": 20,
      "Saude_mental": 30,
      "Dificuldade_caminhar": "Nao",
      "Atividade_fisica": "Sim",
      "Saude_geral": "Muito boa",
      "Horas_sono": 8,
      "Problemas_saude": [
        "diabetes",
        "Asma"
      ]
    }
  ]
}


In [ ]:
pd.json_normalize(dados_dict)


Podemos observar que nossa lista aninhada é colocada em uma única coluna Pacientes. Então, nós usamos o seguinte código para normalizar os dados, especificando qual coluna está aninhada:

In [ ]:
pd.json_normalize(dados_dict['Pacientes'])


Também podemos fazer isso utilizando o parâmetro record_path como ['Pacientes']. Esse parâmetro é usado na função pd.json_normalize() para especificar o caminho para os registros que devem ser normalizados em um DataFrame separado:

In [ ]:
pd.json_normalize(dados_dict, record_path=['Pacientes'])


O resultado parece ótimo, mas não inclui as colunas “Pesquisa” e “Ano”. Para incluí-las, podemos usar o parâmetro meta para especificar outras colunas que queremos no DataFrame.

In [ ]:
pd.json_normalize(
    dados_dict,
    record_path =['Pacientes'],
    meta=['Pesquisa', 'Ano']
)


Dessa forma temos todas as colunas presentes no DataFrame!

Importante: Na aula nós realizamos a normalização em um arquivo com o formato JSON. No entanto, a função json_normalize() aceita apenas um dicionário ou uma lista de dicionários. Por isso, no vídeo foi usada a estratégia de usar o código: pd.json_normalize(dados_pacientes_2['Pacientes']). Porém, se tentarmos usar parâmetros da função json_normalize em um arquivo JSON podem surgir erros. Para contornar isso, precisamos importar o módulo json e ler os arquivos conforme o código abaixo:

In [ ]:
#Importando a biblioteca Pandas
import pandas as pd

#Importando o módulo JSON
import json

#Lendo o arquivo json usando o módulo Python JSON
with open('pacientes_2.json','r') as f:
    dados = json.loads(f.read())

#Normalizando os dados com os parâmetros record_path e meta
pd.json_normalize(dados, record_path='Pacientes', meta=['Pesquisa', 'Ano'])


Para obter dados no formato JSON podemos utilizar uma API (Application Programming Interface). Ela é uma interface de programação de aplicação que permite a comunicação entre diferentes programas ou sistemas.

Atenção: Caso queira aprofundar no assunto, temos um Alura + explicando o que é uma API.

Existem vários formatos que podem ser usados em APIs e um dos mais comuns é o JSON (JavaScript Object Notation). O JSON é um formato leve de troca de informações entre sistemas que utiliza uma notação baseada em objetos do JavaScript.

Nós temos a seguinte situação-problema:

“Uma empresa de alimentos saudáveis está enfrentando um problema com a popularidade de seus produtos. Apesar de oferecer opções saudáveis, muitos(as) clientes estão relutantes em comprar os produtos devido à falta de informação sobre os valores nutricionais das frutas que são utilizadas na produção dos alimentos”.

Nesta situação podemos acessar uma API chamada Fruitvice para coletar informações detalhadas sobre os valores nutricionais das frutas que são usadas nos produtos. Com essas informações, a empresa pode atualizar suas embalagens e materiais de marketing para destacar os valores nutricionais das frutas e, assim, atrair mais clientes que buscam opções saudáveis. Além disso, a empresa pode utilizar as informações para desenvolver novos produtos que atendam ainda mais às necessidades nutricionais de sua clientela.

Uma maneira comum de acessar APIs é por meio da biblioteca requests. Para isso, também é necessário importar o módulo json:

In [ ]:
import requests
import json

Os dados da API Fruitvice serão obtidos com a função request.get('url'). Dentro dela nós passamos o endereço da API seguido de api/fruit/all para obter os dados de todas as frutas.

In [ ]:
dados_frutas = requests.get('https://fruityvice.com/api/fruit/all')

Conseguimos recuperar os resultados usando a função json.loads(). Para isso, é necessário passar a variável dados_frutas, criada anteriormente com o atributo text que retorna o conteúdo da resposta.

In [ ]:
resultado = json.loads(dados_frutas.text)

In [ ]:
pd.DataFrame(resultado)

In [ ]:
import pandas as pd
dados_frutas_normalizado = pd.json_normalize(resultado)

In [ ]:
dados_frutas_normalizado

## Aula 04

HTML (Hypertext Markup Language - Linguagem de marcação de hipertexto) é o código que usamos para estruturar uma página web e seu conteúdo. O HTML consiste em uma série de elementos que são usados para delimitar ou agrupar diferentes partes do conteúdo para que ele apareça ou atue de determinada maneira.

Um documento HTML começa com a tag < html> e termina com a tag < /html>. Ele também contém um cabeçalho (< head>) que descreve o título da página e outras informações relevantes; e um corpo (< body>) que contém o conteúdo da página. O cabeçalho e o corpo são delimitados pelas tags < head> e < /head>, e < body> e < /body>, respectivamente.

Dentro do corpo podemos usar vários elementos para criar a estrutura do conteúdo. Note cada detalhe no exemplo a seguir:

* tags < h1 > a < h6 > : criar títulos e subtítulos.
* tags < p >: criar parágrafos.
* tags < ul > e < li > : criar listas não ordenadas.
* tags < img >: inserir imagens.
* tags < table >, < tr >, < th > e < td >: criar tabelas.
Além disso, podemos usar atributos nos elementos HTML para especificar propriedades adicionais. Por exemplo: podemos usar o atributo src na tag < img > para indicar o endereço da imagem que queremos mostrar, ou o atributo href na tag < a > para indicar o endereço do link que queremos criar.

XML é uma linguagem de marcação que permite criar e descrever dados de forma estruturada e padronizada. Ela é composta por linhas de comandos que usam tags para definir os elementos e os atributos dos dados.

A estrutura básica de um documento XML é formada por:

* Uma declaração inicial que indica a versão, o encoding e o tipo do documento.
* Um elemento raiz que contém todos os outros elementos do documento.
* Elementos filhos que podem ter outros elementos ou conteúdo de texto dentro deles.
* Atributos que fornecem informações adicionais sobre os elementos.

Um exemplo simples de um documento XML é:

In [ ]:
xml
<?xml version="1.0" encoding="UTF-8"?>
<animais>
  <animal nome="Mel" tipo="cachorro" cor="marrom"/>
  <animal nome="Vick" tipo="gato" cor="branco"/>
</animais>

Neste exemplo, <animais> é o elemento raiz, <animal> é um elemento filho com três atributos (nome, tipo e cor) e Mel e Vick são os conteúdos de texto dos elementos.

## Aula 05

Bancos de dados são sistemas que permitem o armazenamento, organização e recuperação de informações de forma estruturada e eficiente. Eles são amplamente utilizados em muitas áreas, desde gerenciamento de negócios à pesquisa científica. Um banco de dados bem projetado pode melhorar significativamente a eficiência e a precisão das operações de uma organização.

Existem bancos de dados relacionais e não-relacionais. Os bancos de dados relacionais representam e armazenam dados em tabelas. Já os não-relacionais, também conhecidos como bancos de dados NoSQL (Not Only SQL - Não SQL), usam uma variedade de estruturas de dados, como documentos, grafos ou pares de chave-valor.

Python oferece vários pacotes e bibliotecas para trabalhar com bancos de dados, incluindo SQLite, MySQL, PostgreSQL, Oracle, MongoDB, entre outros. Um dos pacotes mais comuns usados para trabalhar com bancos de dados relacionais em Python é o pacote sqlite3 que oferece suporte a bancos de dados SQLite. Este banco de dados é leve e incorporado que não exige um servidor separado para ser executado que já vem nativamente instalado no Google Colab.

Para trabalhar com esse banco podemos utilizar a SQLAlchemy, uma biblioteca de mapeamento objeto-relacional (ORM), que possibilita interagir com bancos de dados relacionais usando código Python. Ela fornece uma camada de abstração que permite aos desenvolvedores trabalhar com objetos Python em vez de lidar diretamente com as complexidades da linguagem SQL (Structured Query Language - Linguagem de consulta estruturada).

Uma das principais vantagens do uso de SQLAchemy é a capacidade de criar código mais legível e fácil de manter. Com SQLAlchemy, as operações do banco de dados são executadas usando métodos em objetos Python, tornando o código mais claro e menos propenso a erros.

Além disso, a SQLAlchemy oferece suporte a consultas complexas em bancos de dados, permitindo que pessoas desenvolvedoras extraiam facilmente informações relevantes de grandes conjuntos de dados. Isso é especialmente útil em aplicações que precisam lidar com grandes quantidades de dados.

SQL (Structured Query Language - Linguagem de consulta estruturada) é uma linguagem de consulta utilizada em bancos de dados relacionais para inserir, atualizar, consultar e gerenciar dados.

Para fazer tudo isso,existem as cláusulas SQL, que são componentes fundamentais das instruções SQL, permitindo especificar detalhes sobre como a consulta ou a operação de banco de dados devem ser executadas. As cláusulas são usadas para filtrar, classificar, agrupar e limitar os resultados das consultas.

As instruções SQL podem ser compostas por uma ou mais cláusulas que fornecem informações adicionais sobre o que a consulta deve fazer. As cláusulas mais comuns são:

* SELECT: especifica quais colunas devem ser selecionadas na consulta.
* FROM: especifica as tabelas do banco de dados que devem ser consultadas.
* WHERE: filtra os resultados da consulta com base em uma ou mais condições especificadas.
* ORDER BY: classifica os resultados da consulta em ordem crescente ou decrescente com base em uma ou mais colunas.
* GROUP BY: agrupa os resultados da consulta com base em uma ou mais colunas.
* LIMIT: limita o número de linhas retornadas pelos resultados da consulta.

Temos um exemplo simples de sintaxe SQL que usa o comando SELECT para consultar dados de uma tabela de colaboradores(as) em um banco de dados:

In [70]:
## SELECT nome, sobrenome, salario
## FROM colaboradores
## WHERE departamento = 'vendas'

Nessa instrução SQL, a cláusula SELECT é usada para especificar as colunas que se deseja consultar da tabela "colaboradores", incluindo "nome", "sobrenome" e "salario". A cláusula FROM é usada para especificar a tabela que se deseja consultar, que é "colaboradores" neste caso.

A cláusula WHERE é usada para filtrar os resultados da consulta com base em uma condição especificada. Neste exemplo, a condição é departamento = 'vendas', o que significa que a consulta retornará apenas as pessoas colaboradoras que trabalham no departamento de vendas.